import {
  ArrowDownIcon,
  CheckIcon,
  CrossIcon,
  DotIcon,
  StarIcon,
  ToastErrorIcon,
  ToastInfoIcon,
  ToastSuccessIcon,
  ToastWarningIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  MobileMenuIcon,
  HomeIcon,
  SlashIcon,
  ArrowForwardIcon,
  LocalShippingIcon,
  FavoriteIcon,
  AccountCircleIcon,
  ShoppingBagIcon,
  ErrorOutlineIcon,
  StarOutlinedIcon,
  StarHalfIcon,
  MinusIcon,
  PlusIcon,
  FilterIcon,
  RulerIcon,
  FavoriteOutlinedIcon,
  DeleteOutlinedIcon,
  ProcessingIcon,
  PaymentCardIcon,
  EyeIcon,
  AttachmentIcon,
  UploadIcon,
  FolderIcon,
  FolderOpenIcon,
  WifiTetheringIcon,
  PortraitIcon,
  SearchIcon,
  EditIcon,
  VolumeUpIcon,
  ContentCopyIcon,
  ThumbUpIcon,
  ThumbDownIcon,
  FileCopyIcon,
  KeyboardArrowUp,
  KeyboardArrowDown,
  Send,
  ThumbUpFilled,
  ThumbDownFilled,
  ChatBubbleIcon,
  ChatIcon,
  PhoneIcon,
  MicIcon,
  FullscreenIcon,
  FullscreenExitIcon,
} from '@assets';

export const IconsList = {
  cross: CrossIcon,
  success: ToastSuccessIcon,
  error: ToastErrorIcon,
  warning: ToastWarningIcon,
  info: ToastInfoIcon,
  dot: DotIcon,
  check: CheckIcon,
  arrowDown: ArrowDownIcon,
  arrowRight: ChevronRightIcon,
  arrowLeft: ChevronLeftIcon,
  mobileMenu: MobileMenuIcon,
  home: HomeIcon,
  slash: SlashIcon,
  arrowForward: ArrowForwardIcon,
  localShipping: LocalShippingIcon,
  favorite: FavoriteIcon,
  favoriteOutlined: FavoriteOutlinedIcon,
  deleteOutlined: DeleteOutlinedIcon,
  accountCircle: AccountCircleIcon,
  shoppingBag: ShoppingBagIcon,
  errorOutline: ErrorOutlineIcon,
  star: StarIcon,
  starOutlined: StarOutlinedIcon,
  starHalf: StarHalfIcon,
  minus: MinusIcon,
  plus: PlusIcon,
  filter: FilterIcon,
  ruler: RulerIcon,
  processing: ProcessingIcon,
  paymentCard: PaymentCardIcon,
  eye: EyeIcon,
  attachment: AttachmentIcon,
  upload: UploadIcon,
  folder: FolderIcon,
  folderOpen: FolderOpenIcon,
  wifiTethering: WifiTetheringIcon,
  portrait: PortraitIcon,
  search: SearchIcon,
  edit: EditIcon,
  volumeUp: VolumeUpIcon,
  contentCopy: ContentCopyIcon,
  thumbUp: ThumbUpIcon,
  thumbDown: ThumbDownIcon,
  fileCopy: FileCopyIcon,
  keyboardArrowDown: KeyboardArrowDown,
  keyboardArrowUp: KeyboardArrowUp,
  send: Send,
  thumbUpFilled: ThumbUpFilled,
  thumbDownFilled: ThumbDownFilled,
  chat: ChatIcon,
  chatBubble: ChatBubbleIcon,
  phone: PhoneIcon,
  mic: MicIcon,
  fullscreen: FullscreenIcon,
  fullscreenExit: FullscreenExitIcon,
};

export const COMPONENT_NAME = 'Icon';
