const provider = {
  name: 'ThemeProvider',
  import: "import { ThemeProvider } from 'gd-design-library'",
  description:
    'Context provider component that enables theme support throughout the application, allowing child components to access theme values via useTheme hook.',
  props: [
    {
      name: 'children',
      type: 'React.ReactNode',
      description: 'Child components that will have access to the theme context',
      required: true,
    },
    {
      name: 'initialTheme',
      type: 'Theme',
      description: 'Initial theme object to apply when component mounts',
    },
    {
      name: 'isDefault',
      type: 'boolean',
      description: 'Whether to use the default theme instead of initialTheme',
      default: false,
    },
  ],
  examples: [
    '<ThemeProvider isDefault>{children}</ThemeProvider>',
    '<ThemeProvider initialTheme={customTheme}>{children}</ThemeProvider>',
  ],
};

const hook = {
  name: 'useTheme',
  import: "import { useTheme } from 'gd-design-library'",
  description:
    'Hook for accessing and managing application themes dynamically with support for switching between themes and adding new themes at runtime.',
  props: [
    {
      name: 'theme',
      type: 'Theme',
      description: 'Current active theme object containing all theme tokens and configuration',
      required: true,
    },
    {
      name: 'setTheme',
      type: '(name: string) => void',
      description: 'Function to switch to an existing theme by its name',
    },
    {
      name: 'addTheme',
      type: '(name: string, config: Theme) => void',
      description: 'Function to add a new theme dynamically at runtime',
    },
  ],
  examples: [
    'const { theme, setTheme, addTheme } = useTheme();',
    'const { theme } = useTheme(); // Access current theme values',
    'const { setTheme } = useTheme(); setTheme("dark"); // Switch to dark theme',
    'const { addTheme } = useTheme(); addTheme("custom", customThemeConfig); // Add custom theme',
  ],
};

const compositionTips: string[] = [
  'Use useTheme hook inside ThemeProvider context to access theme values.',
  'Call setTheme to switch between pre-registered themes like light and dark.',
  'Use addTheme to register custom themes dynamically at runtime.',
  'Store theme preference in localStorage and apply on app initialization.',
  'Access theme.colors for consistent color values across components.',
  'Use theme.typography for font sizes, weights, and line heights.',
  'Apply theme.spacing for consistent margins and paddings.',
  'Access theme.breakpoints for responsive design decisions.',
  'Use theme.shadows for consistent elevation and depth effects.',
  'Apply theme.borderRadius for consistent corner rounding.',
  'Access theme.transitions for consistent animation durations.',
  'Use theme.zIndex for consistent layering of overlapping elements.',
  'Apply theme colors to Icon components for theme-aware icons.',
  'Access theme.palette for primary, secondary, and semantic colors.',
  'Use theme.opacity values for consistent transparency effects.',
  'Apply theme.fontFamily for consistent typography across the app.',
  'Access theme.status colors for success, warning, error, and info states.',
  'Use theme.background colors for surface and paper components.',
  'Apply theme.text colors for primary, secondary, and disabled text.',
  'Access theme.action colors for hover, selected, and disabled states.',
  'Use setTheme with user preferences from profile settings.',
  'Apply addTheme to load themes from external configuration files.',
  'Combine useTheme with CSS custom properties for performance.',
  'Use theme.mixins for reusable style combinations.',
  'Apply theme.shape for consistent component shapes and borders.',
  'Access theme.duration for consistent animation and transition timings.',
  'Use setTheme based on system preferences with prefers-color-scheme.',
  'Apply theme values to Canvas or WebGL for theme-aware graphics.',
  'Store multiple theme presets and switch between them with setTheme.',
  'Use theme.components for component-specific theme overrides.',
  'Apply theme values to email templates for consistent branding.',
  'Access theme.gradients for consistent gradient definitions.',
  'Use addTheme to create seasonal or event-specific themes.',
  'Apply theme.backdrop for consistent overlay backgrounds.',
  'Combine useTheme with React.memo for performance optimization.',
  'Use theme values in print stylesheets for consistent printed output.',
  'Apply theme.scrollbar styles for custom scrollbar theming.',
  'Access theme.input styles for consistent form field styling.',
  'Use setTheme in theme switcher components or settings panels.',
  'Apply addTheme with theme builder tools for user customization.',
  'Access theme.divider color for consistent separator styling.',
  'Use theme.contrast ratios for WCAG accessibility compliance.',
  'Apply theme.focus styles for consistent keyboard navigation indicators.',
  'Access theme.disabled opacity for consistent disabled state styling.',
  'Use addTheme to import themes from design system packages.',
  'Apply setTheme with keyboard shortcuts for quick theme switching.',
  'Store theme name in URL params for shareable theme preferences.',
  'Use theme values with styled-components or emotion for dynamic styling.',
  'Apply addTheme validation to ensure theme structure consistency.',
  'Access theme tokens in global styles for consistent base styling.',
  'Use setTheme with animations for smooth theme transitions.',
  'Apply theme configuration to third-party component libraries.',
  'Combine useTheme with context providers for nested theme scoping.',
  'Use addTheme to merge partial theme overrides with base themes.',
];

const themeProviderCompositionTips: string[] = [
  'Wrap ThemeProvider at the root of your application to enable theming.',
  'Use isDefault prop to quickly apply the default theme configuration.',
  'Pass initialTheme prop to start with a custom theme object.',
  'Initialize ThemeProvider with brand-specific theme configurations.',
  'Nest ThemeProvider components to create theme scopes for specific sections.',
  'Combine ThemeProvider with React.Suspense for lazy-loaded themes.',
  'Use ThemeProvider with CSS custom properties for better performance.',
  'Pass dynamic initialTheme based on user profile or preferences.',
  'Initialize ThemeProvider with themes from external configuration.',
  'Use ThemeProvider with feature flags for A/B testing themes.',
  'Combine multiple ThemeProviders for micro-frontend architectures.',
  'Apply ThemeProvider to Storybook stories for theme testing.',
  'Use ThemeProvider with server-side rendering for consistent theming.',
  'Initialize ThemeProvider with seasonal or event-based themes.',
  'Use ThemeProvider with React Context DevTools for debugging.',
  'Combine ThemeProvider with ErrorBoundary for theme fallbacks.',
  'Apply conditional themes based on user roles or permissions.',
  'Use ThemeProvider with React.memo to prevent unnecessary re-renders.',
  'Initialize themes from design tokens or style dictionary.',
  'Apply ThemeProvider to email template previews for consistency.',
  'Use ThemeProvider with portal components for themed modals.',
  'Combine ThemeProvider with internationalization for locale themes.',
  'Apply theme inheritance with nested ThemeProvider components.',
  'Use ThemeProvider with CSS-in-JS libraries like emotion or styled-components.',
  'Initialize ThemeProvider with themes from CMS or database.',
  'Apply ThemeProvider to print preview for themed printing.',
  'Use ThemeProvider with animation libraries for themed transitions.',
  'Combine ThemeProvider with accessibility tools for contrast checking.',
  'Apply different themes for authenticated vs public areas.',
  'Use ThemeProvider with web components for cross-framework theming.',
  'Initialize themes based on time of day or user location.',
  'Apply ThemeProvider to canvas or WebGL contexts for themed graphics.',
  'Use ThemeProvider with form libraries for themed form controls.',
  'Combine ThemeProvider with testing libraries for theme assertions.',
  'Apply brand-specific themes with multi-tenant applications.',
  'Use ThemeProvider with build tools to tree-shake unused themes.',
  'Initialize themes from environment variables for deployment flexibility.',
  'Apply ThemeProvider to iframe content for consistent embedding.',
  'Use ThemeProvider with browser extensions for theme customization.',
  'Combine ThemeProvider with analytics to track theme usage.',
  'Apply responsive themes based on device capabilities.',
  'Use ThemeProvider with service workers for offline theme caching.',
  'Initialize themes from user-generated content or themes marketplace.',
  'Apply ThemeProvider to documentation sites for themed code examples.',
  'Use ThemeProvider with performance monitoring for theme impact analysis.',
  'Combine ThemeProvider with feature toggles for gradual theme rollout.',
  'Apply experimental themes with ThemeProvider for user testing.',
  'Use isDefault when no custom theme is needed for faster initialization.',
  'Pass initialTheme from localStorage for persistent theme preferences.',
  'Combine isDefault with feature detection for fallback theming.',
  'Apply initialTheme validation to ensure theme structure consistency.',
];

export default { hook, provider, compositionTips, themeProviderCompositionTips };
