FROM node:24-alpine AS build
WORKDIR /app

COPY package.json package-lock.json nx.json tsconfig.base.json .npmrc eslint.config.mjs ./
COPY libs/ui/ libs/ui/
COPY bin/export-theme.js bin/export-theme.js

RUN npm ci

RUN npx nx build ui \
 && node ./bin/export-theme.js \
 && npx nx run ui:build-storybook

FROM nginx:alpine AS runner
WORKDIR /usr/share/nginx/html

COPY --from=build /app/libs/ui/storybook-static/ .
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
