export enum TextAlign {
  Start = 'start',
  End = 'end',
  Center = 'center',
  Left = 'left',
  Right = 'right',
  Justify = 'justify',
  MatchParent = 'match-parent',
  Inherit = 'inherit',
  Initial = 'initial',
  Revert = 'revert',
  RevertLayer = 'revert-layer',
  Unset = 'unset',
  WebkitCenter = '-webkit-center',
  MozCenter = '-moz-center',
}

export enum TypographyVariant {
  H1 = 'h1',
  H2 = 'h2',
  H3 = 'h3',
  H4 = 'h4',
  H5 = 'h5',
  H6 = 'h6',
  Body1 = 'p',
  Body2 = 'small',
  Display = 'div',
  Italic = 'i',
  Bold = 'strong',
  Sup = 'sup',
  Sub = 'sub',
  Caption = 'caption',
  Caption2 = 'header',
  Code = 'code',
  Code2 = 'kbd',
  Inherit = 'span',
}

export enum TypographyStyleVariant {
  Bold = 'bold',
  Semibold = 'semibold',
  Normal = 'normal',
  Light = 'light',
  Italic = 'italic',
  Small = 'small',
  Uppercase = 'uppercase',
  Lowercase = 'lowercase',
  Underline = 'underline',
  Strike = 'strike',
}
