import type { Preview } from '@storybook/web-components-vite';

// Generated by the common Storybook workflow, using the production UI build.
// eslint-disable-next-line @nx/enforce-module-boundaries
import '../../../dist/libs/ui/styles.css';
import '../src/index';
import { storySource } from '../stories/helpers';

const preview: Preview = {
  tags: ['autodocs'],
  parameters: {
    layout: 'padded',
    options: { storySort: { order: ['Introduction', 'Atoms', 'Molecules'] } },
    a11y: { test: 'todo' },
    docs: {
      defaultName: 'Docs',
      source: {
        language: 'html',
        transform: (
          source: string,
          context: { canvasElement?: HTMLElement; parameters?: { docs?: { source?: { code?: string } } } }
        ) => (context.parameters?.docs?.source?.code ? source : storySource(context.canvasElement, source)),
      },
    },
  },
};

export default preview;
