import type { Preview } from '@storybook/web-components-vite';

// Generated by the common Storybook workflow, using the production UI build.
// eslint-disable-next-line @nx/enforce-module-boundaries
import '../../../dist/libs/ui/styles.css';
import '../src/index';
import { storySource } from '../stories/helpers';

const preview: Preview = {
  parameters: {
    layout: 'padded',
    options: { storySort: { order: ['Introduction', 'Atoms', 'Molecules'] } },
    a11y: { test: 'todo' },
    docs: {
      source: {
        language: 'html',
        transform: (source: string, context: { canvasElement?: HTMLElement }) =>
          storySource(context.canvasElement, source),
      },
    },
  },
};

export default preview;
