export const styleClasses = {
  label: {
    root: 'fc-label',
    required: 'fc-label-required',
  },
  control: {
    root: 'fc-control',
    label: 'fc-control-label',
    input: 'fc-control-input',
    select: 'fc-control-select',
    error: 'fc-control-error',
    errorMessage: 'fc-error-message',
    warning: 'fc-control-warning',
    warningMessage: 'fc-warning-message',
    disabled: 'fc-control-disabled',
  },
  layout: {
    formGroup: 'fc-form-group',
    root: 'fc-layout',
    element: 'fc-layout-element',
    label: 'fc-layout-label',
  },
  verticalLayout: { root: 'fc-vertical-layout' },
  horizontalLayout: { root: 'fc-horizontal-layout' },
  groupLayout: {
    root: 'fc-group-layout',
    legend: 'fc-group-layout-legend',
  },
  categorizationLayout: {
    root: 'fc-categorization-layout',
    tabs: 'fc-categorization-layout-tabs',
    tab: 'fc-categorization-layout-tab',
    tabContent: 'fc-categorization-layout-tab-content',
    tabPane: 'fc-categorization-layout-tab-pane',
    active: 'active',
  },
  controlContainer: {
    root: 'fc-control-container',
    labelWrapper: 'fc-control-label-wrapper',
    labelText: 'fc-control-label-text',
    labelError: 'fc-control-label-error',
    required: 'fc-control-required',
  },
  arrayControl: {
    root: 'fc-array-control',
    header: 'fc-array-control-header',
    headerTitle: 'fc-array-control-header-title',
    headerCount: 'fc-array-control-header-count',
    emptyState: 'fc-array-control-empty',
    item: 'fc-array-control-item',
    itemContent: 'fc-array-control-item-content',
    itemWrapper: 'fc-array-control-item-wrapper',
    itemLabel: 'fc-array-control-item-label',
    itemActions: 'fc-array-control-item-actions',
    itemErrors: 'fc-array-control-item-errors',
    addButton: 'fc-array-control-add-button',
    removeButton: 'fc-array-control-remove-button',
    validationHint: 'fc-array-control-validation-hint',
    validationWarning: 'fc-array-control-validation-warning',
    validationInfo: 'fc-array-control-validation-info',
  },
  colorControl: {
    root: 'fc-color-control',
    labelWrapper: 'fc-color-control-label-wrapper',
    inputWrapper: 'fc-color-control-input-wrapper',
    colorInput: 'fc-color-control-color-input',
    textInput: 'fc-color-control-text-input',
    preview: 'fc-color-control-preview',
  },
  rangeControl: {
    root: 'fc-range-control',
    header: 'fc-range-control-header',
    labelWrapper: 'fc-range-control-label-wrapper',
    value: 'fc-range-control-value',
    hint: 'fc-range-control-hint',
  },
  fileControl: {
    root: 'fc-file-control',
    label: 'fc-file-control-label',
    hint: 'fc-file-control-hint',
    info: 'fc-file-control-info',
  },
  radioControl: {
    root: 'fc-radio-control',
    labelWrapper: 'fc-radio-control-label-wrapper',
    item: 'fc-radio-control-item',
  },
  checkboxControl: {
    root: 'fc-checkbox-control',
  },
  textareaControl: {
    root: 'fc-textarea-control',
    label: 'fc-textarea-control-label',
    hint: 'fc-textarea-control-hint',
  },
  switchControl: {
    root: 'fc-switch-control',
    labelWrapper: 'fc-switch-control-label-wrapper',
  },
  selectControl: {
    root: 'fc-select-control',
    label: 'fc-select-control-label',
  },
};
