const component = {
  name: 'Breadcrumbs',
  import: "import { Breadcrumbs } from 'gd-design-library'",
  description:
    'Navigation component that displays the current page location within a hierarchical structure, providing users with a trail of links to navigate back to parent pages.',
  a2uiName: 'breadcrumbs',
  category: 'Navigation & Structure',
  complexity: 'Low',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Lightweight',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~1KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'options',
      type: 'Array<{ label: string; value?: string | number; href?: string; disabled?: boolean }>',
      description:
        'Ordered breadcrumb items. Use href for navigable ancestors; omit href on the last item to mark the current page.',
      required: true,
    },
    {
      name: 'separator',
      type: 'string',
      description: 'Text separator rendered between breadcrumb items (for example "/" or ">")',
    },
    {
      name: 'separatorIcon',
      type: 'string',
      description: 'Optional icon name rendered between breadcrumb items instead of a text separator',
    },
    { name: 'icon', type: 'string', description: 'Optional leading icon shown before the breadcrumb trail' },
    { name: 'iconEnd', type: 'string', description: 'Optional trailing icon shown after the breadcrumb trail' },
    {
      name: 'separatorAfterLastItem',
      type: 'boolean',
      description: 'Whether to show a separator after the last item',
      default: false,
    },
    { name: 'bordered', type: 'boolean', description: 'Whether to show a bordered container around the breadcrumbs' },
    {
      name: 'ariaLabel',
      type: 'string',
      description: 'Accessible label for the breadcrumbs nav element (e.g. "Page navigation")',
    },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the breadcrumbs container' },
  ],
  quickStart: {
    basic:
      '<Breadcrumbs items={[<Link href="/">Home</Link>, <Link href="/products">Products</Link>, <Typography>Detail</Typography>]} />',
    withIcon: '<Breadcrumbs items={breadcrumbItems} separator={<Icon name="chevronRight" />} />',
    bordered: '<Breadcrumbs items={paths} bordered itemStart={<Icon name="home" />} />',
    custom: '<Breadcrumbs items={paths} separator=">" ariaLabel="Page navigation" />',
  },
  commonPatterns: {
    'E-commerce': {
      code: '<Breadcrumbs items={[<Link href="/">Home</Link>, <Link href="/electronics">Electronics</Link>, <Link href="/electronics/smartphones">Smartphones</Link>, <Typography>iPhone 15</Typography>]} />',
      useCase: 'Product pages with category hierarchy',
    },
    Documentation: {
      code: '<Breadcrumbs items={[<Link href="/docs">Docs</Link>, <Link href="/docs/api">API</Link>, <Typography>Authentication</Typography>]} />',
      useCase: 'Documentation sites with nested sections',
    },
    'Admin Panel': {
      code: '<Breadcrumbs items={[<Link href="/admin">Dashboard</Link>, <Link href="/admin/users">Users</Link>, <Typography>Edit User</Typography>]} />',
      useCase: 'Administrative interfaces with deep navigation',
    },
  },
  examples: [
    '<Breadcrumbs items={[<Link href="/">Home</Link>, <Link href="/products">Products</Link>, <Typography>Detail</Typography>]} />',
    '<Breadcrumbs items={breadcrumbItems} separator={<Icon name="chevronRight" />} bordered />',
    '<Breadcrumbs items={paths} itemStart={<Icon name="home" />} ariaLabel="Page navigation" />',
  ],
  troubleshooting: {
    'Links not working': 'Pass pre-built Link components with href in the items array for navigation',
    'Separator not showing': 'Verify separator prop is set correctly',
    'Accessibility issues': 'Provide proper ariaLabel and ensure keyboard navigation works',
    'Items not displaying': 'Check items array contains valid ReactNode elements (Link, Typography, etc.)',
    'Styling issues': 'Use bordered prop for visual separation and consistent className',
  },
  bestPractices: [
    'Use at the top of content pages to show hierarchical navigation path',
    'Pass Link components with href for parent pages and Typography (no href) for current page',
    'Apply separator with Icon component for visual separators like chevronRight',
    'Use itemStart with home icon for clear navigation starting point',
    'Set bordered={true} to visually separate from page content',
    'Apply consistent positioning across all pages for user orientation',
    'Use Link components with onClick for client-side routing in SPAs',
    'Combine with Typography variant="caption" as="span" for items in compact layouts',
    'Apply ariaLabel with descriptive text for screen reader context',
    'Keep items concise with truncation for long labels in deep hierarchies',
  ],
};

const compositionTips: string[] = [
  'Use Breadcrumbs at the top of content pages to show hierarchical navigation path.',
  'Pass Link components with href for parent pages and Typography (no link) for the current page as the last item.',
  'Apply Breadcrumbs separator with Icon component for visual separators like chevronRight.',
  'Use Breadcrumbs itemStart with home icon for clear navigation starting point.',
  'Set Breadcrumbs bordered={true} to visually separate from page content.',
  'Apply Breadcrumbs with consistent positioning across all pages for user orientation.',
  'Use Link components with onClick instead of href for client-side routing in SPAs.',
  'Combine Breadcrumbs with Typography variant="caption" as="span" for items in compact layouts.',
  'Set Breadcrumbs separatorAfterLastItem={false} (default) for clean ending.',
  'Apply Breadcrumbs ariaLabel with descriptive text for screen reader context.',
  'Use Breadcrumbs itemEnd with status icons or badges for additional context.',
  'Keep Breadcrumbs items concise with truncation for long labels in deep hierarchies.',
  'Apply Breadcrumbs className for consistent styling across the application.',
  'Use Breadcrumbs with responsive design hiding middle items on mobile with ellipsis.',
  'Build items array dynamically from route parameters: paths.map((p, i) => i < paths.length - 1 ? <Link href={p.href}>{p.label}</Link> : <Typography>{p.label}</Typography>).',
  'Apply Breadcrumbs with Link component styling for consistent link appearance.',
  'Use Breadcrumbs separator=">" for simple text separators without icons.',
  'Combine Breadcrumbs with page title Typography for complete page context.',
  'Apply Breadcrumbs with schema.org structured data for SEO benefits.',
  'Use Breadcrumbs items with conditional rendering based on user permissions.',
  'Set Breadcrumbs with max-width and overflow for very long paths.',
  'Apply Breadcrumbs consistently below header and above main content.',
  'Use Breadcrumbs with tooltip on truncated items to show full path.',
  'Combine Breadcrumbs with router hooks to automatically generate items.',
  'Apply Breadcrumbs with keyboard navigation support for accessibility.',
  'Use Icon components inside items array for visual category identification.',
  'Set Breadcrumbs with appropriate font size using Typography for readability.',
  'Apply Breadcrumbs with home link as first item for consistent navigation.',
  'Use Breadcrumbs separator with custom spacing for better visual rhythm.',
  'Combine Breadcrumbs with loading state while fetching dynamic path data.',
  'Apply Breadcrumbs with proper contrast ratios for accessibility compliance.',
  'Set Breadcrumbs with sticky positioning for long scrolling pages.',
  'Apply Breadcrumbs with breadcrumb microdata for search engine rich snippets.',
  'The last item in the items array should be plain Typography (no link) to indicate the current page.',
  'Combine Breadcrumbs with animation for smooth transitions between pages.',
  'Apply Breadcrumbs with consistent separator style throughout the application.',
  'Use Breadcrumbs with collapsible middle items for mobile-friendly navigation.',
  'Apply Breadcrumbs with hover states on clickable Link items for better UX.',
];

export default { component, compositionTips };
