const component = {
  name: 'Carousel',
  import: "import { Carousel } from 'gd-design-library'",
  description:
    'Container component for displaying a series of content in a scrollable format with navigation controls. Supports horizontal and vertical layouts with touch/swipe, keyboard navigation, and customizable slide dimensions. In A2UI, use this for prompts like image gallery, gallery, slider, slideshow, or "generate carousel 7 images", and whenever vertical layout or a single focused image sequence is requested.',
  a2uiName: 'carousel',
  category: 'Navigation & Display',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  a2uiSubcomponents: {
    'carousel-slide': {
      component: 'Carousel.Slide',
      props: [
        {
          name: 'children',
          type: 'A2UIComponent[]',
          description:
            'Slide content. For image carousels, place a single "image" child inside each "carousel-slide". Direct "image" children on the carousel root are also supported.',
        },
        { name: 'styling', type: 'object', description: 'CSS style overrides for the slide wrapper' },
      ],
    },
  },
  props: [
    {
      name: 'children',
      type: 'A2UIComponent[]',
      description:
        'Carousel slide content. In A2UI, use direct "image" children or "carousel-slide" wrappers containing one "image" child.',
      required: true,
    },
    {
      name: 'layout',
      type: 'string',
      description: 'Scroll direction of the carousel',
      enum: ['horizontal', 'vertical'] as const,
      default: 'horizontal',
    },
    {
      name: 'variant',
      type: 'string',
      description: 'Visual variant of the carousel',
      enum: ['cards', 'single'] as const,
    },
    { name: 'showArrows', type: 'boolean', description: 'Whether to show previous/next arrow navigation buttons' },
    { name: 'showDots', type: 'boolean', description: 'Whether to show dot indicators for each slide' },
    {
      name: 'thumbs',
      type: 'string',
      description: 'Position of thumbnail navigation strip relative to main carousel',
      enum: ['start', 'end'] as const,
    },
    { name: 'isFocusable', type: 'boolean', description: 'Whether slides can receive keyboard focus' },
    {
      name: 'carouselOptions',
      type: 'object',
      description: 'Optional Embla carousel options such as loop or align. Only used by type "carousel".',
    },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the carousel container' },
  ],
  examples: [
    '<Carousel showDots={true}><Carousel.Slide><Image src="/slide1.jpg" /></Carousel.Slide><Carousel.Slide><Image src="/slide2.jpg" /></Carousel.Slide></Carousel>',
    '<Carousel layout="vertical" styling={{height: "400px"}}>{slides}</Carousel>',
    '<Carousel showArrows={false} showDots={true} options={{loop: true}}>{productImages.map(img => <Carousel.Slide key={img.id}><Carousel.Image src={img.url} /></Carousel.Slide>)}</Carousel>',
    '<Carousel variant="cards" showArrows>{cards}</Carousel>',
  ],
};

const compositionTips: string[] = [
  'Use showDots for quick navigation on mobile; showArrows for desktop-sized carousels.',
  'In A2UI, prefer Carousel for prompts that say image gallery, gallery, slider, slideshow, or a plain image-only carousel like "generate carousel 7 images".',
  'Enable options={{loop: true}} for galleries; disable for step-based content walkthroughs.',
  'Use onSlideChange for analytics or syncing external state.',
  'Use Carousel with showDots={true} for mobile interfaces where arrow buttons might be too small for touch targets.',
  'Apply Carousel layout="horizontal" (default) for image galleries and product showcases.',
  'Set Carousel layout="vertical" for testimonials or feature lists that benefit from vertical scrolling.',
  'Use Carousel.Slide wrapper for each slide to ensure proper slide behavior and styling.',
  'Apply Carousel.Image for optimized image slides with proper aspect ratio handling.',
  'Use Carousel options={{loop: true, autoplay: true}} for hero banners and promotional content.',
  'Use Carousel options={{loop: true}} for continuous browsing experience in image galleries.',
  'Use Carousel showArrows={false} on mobile to rely on touch gestures for navigation.',
  'Combine Carousel with Card components inside slides for structured content presentation.',
  'Apply Carousel styling={{height: "400px"}} with fixed value to prevent layout shifts during slide transitions.',
  'Use Carousel onSlideChange to update external UI elements like slide counters or descriptions.',
  'Apply Carousel styling with overflow settings for edge-bleeding slide effects.',
  'Use Carousel with responsive styling for adaptive layouts across screen sizes.',
  'Combine Carousel with lazy loading for performance optimization with many image slides.',
  'Apply Carousel padding to create space around the visible slide area for peek effects.',
  'Use Carousel with keyboard navigation support for accessibility compliance.',
  'Set Carousel with touch and swipe gestures enabled by default for mobile usability.',
  'Apply Carousel inside Modal for image lightbox and gallery viewing experiences.',
  'Use Carousel with thumbnail navigation below main carousel for image galleries.',
  'If a prompt asks for a vertical gallery or vertical slider, use Carousel rather than ContentCarousel.',
  'Combine Carousel with video content using proper pause/play on slide change.',
  'Apply Carousel with consistent aspect ratios across slides to prevent jarring transitions.',
  'Use Carousel showDots with custom dot styling for brand-aligned indicators.',
  'Set Carousel with aria-labels for screen reader navigation announcements.',
  'Apply Carousel with fade transitions instead of slide for smoother visual effects.',
  'Use Carousel in hero sections with full-width layout and background images.',
  'Combine Carousel with progressive loading for better perceived performance.',
  'Apply Carousel with pause on hover for autoPlay to improve user control.',
  'Use Carousel with dynamic children array for data-driven slide generation.',
  'Set Carousel with responsive showArrows hiding arrows on small screens.',
  'Apply Carousel with infinite scroll pattern using loop and dynamic content loading.',
  'Use Carousel for step-by-step tutorials with navigation controls for user pacing.',
  'Combine Carousel with form steps for multi-step form wizards.',
  'Apply Carousel with synchronized controls for multiple related carousels.',
  'Use Carousel with auto height via styling for content-driven height with variable slide content.',
  'Set Carousel with preload strategies for adjacent slides to ensure smooth transitions.',
  'Apply Carousel with custom navigation using external buttons via ref methods.',
  'Use Carousel for comparison views with side-by-side product features.',
  'Combine Carousel with zoom functionality for detailed product image inspection.',
  'Apply Carousel with slide counters showing "1 of 5" style position indicators.',
  'Use Carousel in testimonial sections with automatic rotation for social proof.',
  'Set Carousel with reduced motion preferences for accessibility considerations.',
  'Apply Carousel with analytics tracking on slide views and interactions.',
  'Use Carousel for date/time pickers with vertical or horizontal scrolling.',
  'Combine Carousel with filters to dynamically update displayed slides.',
  'Apply Carousel with skeleton loaders while slide content is being fetched.',
  'Use Carousel for onboarding flows with clear progression through steps.',
  'Set Carousel with custom slide animations for branded experiences.',
];

export default { component, compositionTips };
