const component = {
  name: 'ChatBubble',
  import: "import { ChatBubble } from 'gd-design-library'",
  description:
    'Chat message bubble component for displaying conversation messages with distinct styling for questions and answers, optional action buttons, and status indicators for message states.',
  a2uiName: 'chat-bubble',
  a2uiSubcomponents: {
    'chat-image-gallery': {
      component: 'ChatBubble.ImageGallery',
      props: [
        {
          name: 'images',
          type: 'Array<{ src: string; alt?: string }>',
          description:
            'Images to display in the 2x2 grid. Items beyond maxVisible roll up into a "+N" overlay on the last visible tile.',
          required: true,
        },
        {
          name: 'maxVisible',
          type: 'number',
          description: 'Maximum tiles to render before the "+N" overlay appears (default 4).',
          default: 4,
        },
        {
          name: 'actions',
          type: 'string[]',
          description: 'Optional action IDs triggered when a tile is clicked. Payload includes the clicked index.',
        },
        { name: 'styling', type: 'object', description: 'CSS style overrides' },
      ],
    },
  },
  category: 'Communication & Chat',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~2KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'variant',
      type: 'string',
      description: 'Visual style: "question" for user messages, "answer" for agent responses',
      enum: ['question', 'answer'] as const,
      default: 'question',
    },
    {
      name: 'children',
      type: 'A2UIComponent[]',
      description:
        'Optional rich child content rendered inside the bubble after the main text. Use label or value for plain message text.',
    },
    {
      name: 'status',
      type: 'string',
      description:
        'Message generation status — "pending" while streaming/generating, "fulfilled" when complete, "rejected" when generation fails',
      enum: ['pending', 'fulfilled', 'rejected'] as const,
    },
    {
      name: 'actionChildren',
      type: 'A2UIComponent[]',
      description: 'Components rendered below the message body in the dedicated action row.',
    },
    {
      name: 'size',
      type: 'string',
      description: 'Size of the chat bubble',
      enum: ['sm', 'md', 'lg'] as const,
    },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the chat bubble' },
  ],
  quickStart: {
    question: '<ChatBubble variant="question">How can I help you today?</ChatBubble>',
    answer: '<ChatBubble variant="answer">Here is the answer to your question.</ChatBubble>',
    pending: '<ChatBubble variant="answer" status="pending">Typing response...</ChatBubble>',
    withActions:
      '<ChatBubble variant="answer" status="fulfilled" actions={[<Button variant="text">Copy</Button>, <Button variant="text">Share</Button>]}>Here is the answer.</ChatBubble>',
  },
  commonPatterns: {
    'User Question': {
      code: '<ChatBubble variant="question">What is the weather like today?</ChatBubble>',
      useCase: 'User messages in chat interfaces',
    },
    'AI Response': {
      code: '<ChatBubble variant="answer" status="fulfilled" actions={[<Button variant="text">Copy</Button>]}>The weather is sunny with 75°F temperature.</ChatBubble>',
      useCase: 'AI or bot responses with action buttons',
    },
    'Typing Indicator': {
      code: '<ChatBubble variant="answer" status="pending">Typing response...</ChatBubble>',
      useCase: 'Loading states while generating responses',
    },
    'System Message': {
      code: '<ChatBubble variant="answer" actions={[<Button variant="text">Dismiss</Button>]}>System maintenance scheduled for tonight.</ChatBubble>',
      useCase: 'System notifications and alerts in chat',
    },
  },
  examples: [
    '<ChatBubble variant="question">How can I help you today?</ChatBubble>',
    '<ChatBubble variant="answer" status="pending">Typing response...</ChatBubble>',
    '<ChatBubble variant="answer" status="fulfilled" actions={[<Button variant="text">Copy</Button>, <Button variant="text">Share</Button>]}>Here is the answer to your question.</ChatBubble>',
    '<ChatBubble variant="question" actions={[<Button variant="text" size="sm">Edit</Button>]}>What is the weather like?</ChatBubble>',
  ],
  troubleshooting: {
    'Actions not showing': 'Check actions prop array and ensure Button components are properly imported',
    'Status not updating': 'Verify status prop is set correctly (pending, fulfilled, undefined)',
    'Styling issues': 'Check variant prop (question vs answer) for proper styling',
    'Accessibility issues': 'Ensure proper ARIA labels and keyboard navigation support',
    'Content not displaying': 'Check children prop and ensure content is provided',
  },
  bestPractices: [
    'Use variant="question" for user messages and variant="answer" for AI/agent responses',
    'Apply status="pending" with loading indicator or typing animation while generating responses',
    'Set status="fulfilled" when message is fully loaded and ready for interaction',
    'Use actions prop with copy, share, or feedback buttons for message interactions',
    'Apply within ChatContainer children wrapped in Column for proper message spacing',
    'Combine with Avatar component to show sender identity in multi-user chats',
    'Use with timestamp using Typography variant="caption" as="div" for message metadata',
    'Apply variant styling consistently to distinguish between sender and receiver messages',
    'Set actions with icon-only Button components for compact action bars',
    'Use conditional rendering of actions based on message type or user permissions',
  ],
};

const compositionTips: string[] = [
  'Use ChatBubble variant="question" for user messages and variant="answer" for AI/agent responses in chat interfaces.',
  'Apply ChatBubble status="pending" with loading indicator or typing animation while generating responses.',
  'Set ChatBubble status="fulfilled" when message is fully loaded and ready for interaction.',
  'Use ChatBubble actions prop with copy, share, or feedback buttons for message interactions.',
  'Apply ChatBubble within ChatContainer children wrapped in Column for proper message spacing.',
  'Combine ChatBubble with Avatar component to show sender identity in multi-user chats.',
  'Use ChatBubble with timestamp using Typography variant="caption" as="div" for message metadata.',
  'Apply ChatBubble variant styling consistently to distinguish between sender and receiver messages.',
  'Set ChatBubble actions with icon-only Button components for compact action bars.',
  'Use ChatBubble with conditional rendering of actions based on message type or user permissions.',
  'Apply ChatBubble with markdown or rich text rendering in children for formatted messages.',
  'Combine multiple ChatBubble components with Separator for date or session breaks.',
  'Use ChatBubble status="pending" with Skeleton or dots loader for realistic typing indicators.',
  'Apply ChatBubble with error state styling when message fails to send or load.',
  'Set ChatBubble with max-width constraints for better readability on wide screens.',
  'Use ChatBubble variant="question" aligned to right and variant="answer" to left for visual flow.',
  'Apply ChatBubble with smooth scroll-to-bottom behavior when new messages appear.',
  'Combine ChatBubble with InlineNotification for system messages or alerts within chat.',
  'Use ChatBubble actions with tooltips for action button descriptions on hover.',
  'Apply ChatBubble with code syntax highlighting when displaying code snippets in messages.',
  'Set ChatBubble with responsive padding and font sizes for mobile chat interfaces.',
  'Use ChatBubble with message editing capability by replacing children content on edit action.',
  'Apply ChatBubble with message threading support using indentation or visual connectors.',
  'Combine ChatBubble with file attachments using Card or Image components within children.',
  'Use ChatBubble variant colors from theme for consistent brand appearance.',
  'Apply ChatBubble with keyboard navigation support for accessible message interactions.',
  'Set ChatBubble with auto-retry mechanism for failed messages with status tracking.',
  'Use ChatBubble with real-time status updates via WebSocket for live chat experiences.',
  'Apply ChatBubble with message reactions using emoji buttons in actions array.',
  'Combine ChatBubble with voice message playback controls when displaying audio messages.',
  'Use ChatBubble with link preview cards when URLs are detected in message content.',
  'Apply ChatBubble with message grouping for consecutive messages from same sender.',
  'Set ChatBubble with delivery receipts using status indicators below messages.',
  'Use ChatBubble with translation actions for multi-language chat support.',
  'Apply ChatBubble with context menu on right-click for additional message options.',
  'Combine ChatBubble with typing indicators showing multiple users typing simultaneously.',
  'Use ChatBubble with message search highlighting for finding specific content.',
  'Apply ChatBubble with collapsible long messages using "Show more" buttons.',
  'Set ChatBubble with consistent border-radius matching overall app design language.',
  'Use ChatBubble variant="answer" with streaming text effect for AI responses.',
  'Apply ChatBubble with message pinning capability for important messages.',
  'Combine ChatBubble with user mentions using @ symbols with autocomplete.',
  'Use ChatBubble with message forwarding actions to share across conversations.',
  'Apply ChatBubble with read receipts showing user avatars who have read the message.',
  'Set ChatBubble with animated entrance effects for smooth message appearance.',
  'Use ChatBubble with quick reply suggestions as clickable chips below messages.',
  'Apply ChatBubble with message encryption indicators for secure conversations.',
  'Combine ChatBubble with location sharing displaying maps within message content.',
  'Use ChatBubble with message scheduling showing future send times.',
];

export default { component, compositionTips };
