const component = {
  name: 'ContentCarousel',
  import: "import { ContentCarousel } from 'gd-design-library'",
  description:
    'Production-ready horizontal carousel component with smart navigation, accessibility, and touch support. Built on Embla Carousel with item-by-item scrolling, keyboard navigation, and responsive design. Use for product galleries, testimonials, team showcases, image collections, or any repeated horizontal content. In A2UI, prefer this over "carousel" for prompts like "generate carousel 5 image items", "carousel of cards", "carousel of text blocks", "carousel of blocks", or other repeated horizontal item collections that explicitly say items/cards/blocks/text. Plain image-only carousel prompts should use "carousel" instead. In A2UI JSON, encode slide content in children[] and never emit React-only items/renderItem fields.',
  a2uiName: 'content-carousel',
  category: 'Navigation & Display',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized for large datasets',
  dependencies: ['@emotion/react', '@emotion/styled', 'embla-carousel-react'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~15KB gzipped',
  browserSupport: 'Modern browsers (ES2015+)',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'children',
      type: 'A2UIComponent[]',
      description:
        'Repeated slide content. In A2UI, provide children[] of "image", "card", "carousel-slide", typography blocks, or other supported slide content. Do not use items or renderItem.',
      required: true,
    },
    { name: 'showArrows', type: 'boolean', description: 'Whether to show previous/next arrow navigation buttons' },
    { name: 'showDots', type: 'boolean', description: 'Whether to show dot indicators' },
    { name: 'isFocusable', type: 'boolean', description: 'Whether slides can receive keyboard focus' },
    { name: 'visibleItems', type: 'number', description: 'Number of slides visible at once', default: 1 },
    { name: 'scrollStep', type: 'number', description: 'Number of items to scroll per navigation action', default: 1 },
    {
      name: 'scrollAlignment',
      type: 'string',
      description: 'Alignment of the active slide within the viewport',
      enum: ['left', 'centered'] as const,
    },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the carousel container' },
  ],
  quickStart: {
    basic: '{ type: "content-carousel", children: [{ type: "card", ... }] }',
    withNavigation: '{ type: "content-carousel", showArrows: true, showDots: true, children: [{ type: "card", ... }] }',
    multipleVisible: '{ type: "content-carousel", visibleItems: 3, scrollStep: 1, children: [{ type: "card", ... }] }',
    centered:
      '{ type: "content-carousel", visibleItems: 3, scrollAlignment: "centered", isFocusable: true, children: [{ type: "image", ... }] }',
    customScrollStep: '{ type: "content-carousel", visibleItems: 3, scrollStep: 2, children: [{ type: "card", ... }] }',
  },
  commonPatterns: {
    'Product Gallery': {
      code: '{ type: "content-carousel", showArrows: true, showDots: true, visibleItems: 3, scrollStep: 1, children: [{ type: "card", children: [{ type: "image", ... }, { type: "card-column", ... }] }] }',
      useCase: 'E-commerce product showcases with images and pricing',
    },
    Testimonials: {
      code: '{ type: "content-carousel", showDots: true, isFocusable: true, visibleItems: 2, children: [{ type: "card", children: [{ type: "typography", ... }, { type: "typography", ... }] }] }',
      useCase: 'Customer testimonials with quotes and author information',
    },
    'Team Members': {
      code: '{ type: "content-carousel", showArrows: true, children: [{ type: "card", children: [{ type: "avatar", ... }, { type: "card-column", ... }] }] }',
      useCase: 'Team member showcases with photos and roles',
    },
    'Image Item Strip': {
      code: '{ type: "content-carousel", showDots: true, isFocusable: true, scrollAlignment: "centered", children: [{ type: "image", src: "...", alt: "Gallery image" }] }',
      useCase:
        'Repeated horizontal image items when the request explicitly says image items rather than a plain image carousel',
    },
  },
  examples: [
    '{ type: "content-carousel", showArrows: true, showDots: true, visibleItems: 3, children: [{ type: "card", ... }] }',
    '{ type: "content-carousel", showDots: true, isFocusable: true, visibleItems: 2, scrollAlignment: "centered", children: [{ type: "card", ... }] }',
    '{ type: "content-carousel", showArrows: true, visibleItems: 2, scrollStep: 2, children: [{ type: "flex-container", ... }] }',
    '{ type: "content-carousel", showDots: true, isFocusable: true, scrollAlignment: "centered", children: [{ type: "image", src: "...", alt: "Gallery image" }] }',
    '{ type: "content-carousel", showArrows: true, visibleItems: 4, children: [{ type: "card", ... }] }',
  ],
  troubleshooting: {
    'Items not rendering':
      'Ensure children[] contains supported A2UI components such as image, card, or carousel-slide.',
    'Navigation not working': 'Check if showArrows or showDots are enabled, and children[] has content',
    'Accessibility issues':
      'Set isFocusable={true} and ensure each child component is accessible content with labels or alt text where needed',
    'Performance issues': 'Use scrollStep={1} for item-by-item navigation, visibleItems to limit rendered items',
    'Touch gestures not working': 'Ensure container has proper touch event handling and sufficient space',
  },
  bestPractices: [
    'Always use isFocusable={true} for accessibility compliance',
    'Use scrollStep={1} for item-by-item navigation (default), scrollStep={2} or {3} to scroll multiple item widths',
    'Set visibleItems to show multiple items side-by-side (e.g., visibleItems={3})',
    'Use scrollAlignment="left" for default left-aligned navigation, "centered" for single item focus',
    'Set showArrows={false} on mobile devices, rely on touch gestures',
    'Use showDots for mobile, showArrows for desktop',
    'Include proper alt text in image children',
    'Use consistent item heights to prevent layout shifts',
    'In A2UI, never emit React-only items or renderItem fields; use children[] only',
    'Use Card components in children[] for consistent styling',
    'Add loading states while data is being fetched',
    'Use unique child ids for stable rendering',
  ],
  capabilities: {
    'Navigation & Controls': [
      'Smart navigation with scrollStep prop for customizable item scrolling (default: 1)',
      'Visible items control with visibleItems prop to show multiple items simultaneously',
      'Scroll alignment options: centered (default), left, or right alignment',
      'Arrow navigation with customizable positioning and disabled states',
      'Dot indicators with active state visualization and direct navigation',
      'Touch/swipe gestures with momentum scrolling and snap behavior',
      'Keyboard navigation with arrow keys, Home, End, and Page Up/Down support',
      'Focus management with proper tab order and accessibility support',
    ],
    'Content & Rendering': [
      'Generic TypeScript support for any data type with custom rendering',
      'Flexible repeated slide content through children[]',
      'Dynamic content loading optimized for large datasets',
      'Responsive layout that adapts to different screen sizes',
      'Performance optimized with minimal re-renders and memory usage',
    ],
    'Accessibility & UX': [
      'WCAG 2.1 AA compliant with ARIA landmarks and screen reader support',
      'Keyboard navigation with logical tab order and focus indicators',
      'High contrast mode support and reduced motion preferences',
      'Touch accessibility with appropriate touch targets and gesture alternatives',
      'Smooth animations and transitions for enhanced user experience',
    ],
    'Customization & Theming': [
      'Complete design token system with customizable styling',
      'Theme integration with consistent design system colors and spacing',
      'Custom styles support for brand-specific carousel appearance',
      'Responsive behavior with different layouts across device types',
      'Event handling for slide changes and user interactions',
    ],
  },
  useCases: {
    'E-commerce & Shopping': [
      'Product galleries with zoom support and detailed views',
      'Featured product showcases with pricing and availability',
      'Category browsers with filtering and sorting options',
      'Related products suggestions with cross-selling opportunities',
      'Product image carousels with thumbnail navigation',
    ],
    'Content & Media': [
      'Image galleries with full-screen viewing and sharing',
      'Video previews with play controls and progress indicators',
      'Blog post previews with author information and read times',
      'News article carousels with trending topics and categories',
      'Social media feeds with post interactions and engagement metrics',
    ],
    'Business & Professional': [
      'Team member showcases with roles and contact information',
      'Client testimonials with ratings and company information',
      'Case study presentations with project details and outcomes',
      'Service offerings with pricing tiers and feature comparisons',
      'Portfolio items with project descriptions and technologies used',
    ],
    'Data & Analytics': [
      'Chart carousels with different visualization types',
      'Dashboard widgets with real-time data updates',
      'Report summaries with key metrics and insights',
      'Performance indicators with trend analysis and comparisons',
      'Data visualization with interactive elements and drill-down capabilities',
    ],
  },
};

const compositionTips: string[] = [
  'Use scrollStep={1} for item-by-item navigation (default), scrollStep={2} or {3} to scroll multiple item widths.',
  'In A2UI, prefer ContentCarousel for prompts that ask for a carousel of multiple items, cards, text blocks, or blocks; plain image-only carousel prompts should use Carousel instead.',
  'In A2UI, encode slide content in children[] and never emit items or renderItem.',
  'Set visibleItems={3} to show multiple items side-by-side for better content visibility.',
  'Use scrollAlignment="left" for default left-aligned navigation, scrollAlignment="centered" for single item focus.',
  'Apply ContentCarousel with Card components in children[] for structured content presentation with consistent styling.',
  'Set showArrows and showDots based on device type - dots for mobile touch, arrows for desktop precision.',
  'Use isFocusable={true} for keyboard navigation support improving accessibility and power user experience.',
  'Use ContentCarousel with Avatar components in children[] for team member or user profile carousels.',
  'Set fixed height child items to prevent layout shifts and ensure smooth transitions.',
  'Apply ContentCarousel for repeated image items only when the prompt explicitly says image items; plain image carousels should use Carousel.',
  'Use filtered or conditionally built children[] content for dynamic carousels based on user selections or categories.',
  'Combine ContentCarousel with Typography components in children[] for text-based content slides.',
  'Apply ContentCarousel with Icon components in children[] for feature or benefit highlight carousels.',
  'Use ContentCarousel with Button components in children[] for actionable slide content with clear CTAs.',
  'Set ContentCarousel with consistent aspect ratios across children for smooth visual transitions.',
  'Apply ContentCarousel for blog post previews with card children showing thumbnails and excerpts.',
  'Use ContentCarousel with Badge components in children[] for items with status indicators or categories.',
  'Combine ContentCarousel with FlexContainer in children[] for complex slide layouts with multiple elements.',
  'Apply ContentCarousel for testimonial sections with card children showing quotes, authors, and ratings.',
  'Use ContentCarousel for product showcases with card children containing pricing and details.',
  'Set ContentCarousel children with proper aria labels or alt text for screen reader accessibility and better UX.',
  'Apply ContentCarousel for portfolio items with card children displaying project descriptions.',
  'Use ContentCarousel with video content children, pausing on slide change for better performance.',
  'Combine ContentCarousel with Modal triggers inside children for detailed views and expanded content.',
  'Apply ContentCarousel for social media feeds with children showing posts with engagement metrics.',
  'Use ContentCarousel with progress indicators when items represent steps, stages, or sequential content.',
  'Set ContentCarousel with onClick handlers on children for clickable slides with navigation or actions.',
  'Apply ContentCarousel for pricing plans with card children showing feature comparisons.',
  'Use ContentCarousel with loading skeleton children while data is being fetched for better UX.',
  'Combine ContentCarousel with InlineNotification children for items with status messages or alerts.',
  'Apply ContentCarousel for category showcases with card children displaying icons.',
  'Use ContentCarousel for timeline events with children showing chronological items and dates.',
  'Set ContentCarousel with hover effects on children for interactive slides with visual feedback.',
  'Apply ContentCarousel for data visualization with children showing charts and metrics.',
  'Use ContentCarousel with Separator inside children for visually divided content sections.',
  'Set ContentCarousel with responsive gap values for mobile vs desktop spacing consistency.',
  'Apply ContentCarousel for news articles with card children showing headlines.',
  'Use ContentCarousel with consistent child styling matching your design system tokens.',
  'Combine ContentCarousel with lazy loading inside children for performance optimization with large datasets.',
  'Apply ContentCarousel for service offerings with card children showing descriptions.',
  'Use ContentCarousel with unique child ids for stable rendering and proper re-rendering.',
  'Set ContentCarousel with custom styles for brand-specific carousel appearance and theming.',
  'Apply ContentCarousel for case studies with card children showing project details and outcomes.',
];

export default { component, compositionTips };
