const component = {
  name: 'Counter',
  import: "import { Counter } from 'gd-design-library'",
  description:
    'Numeric input component with increment/decrement controls for selecting values within a defined range. Provides accessible controls for quantity selection, settings adjustment, or any numeric value input.',
  a2uiName: 'counter',
  category: 'Forms & Input',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~2KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    { name: 'initial', type: 'number', description: 'Starting value of the counter' },
    { name: 'min', type: 'number', description: 'Minimum allowed value (decrement button disables at this value)' },
    { name: 'max', type: 'number', description: 'Maximum allowed value (increment button disables at this value)' },
    {
      name: 'disabled',
      type: 'boolean',
      description: 'Whether the counter is disabled',
    },
    {
      name: 'actions',
      type: 'string[]',
      description: 'Action IDs from ui.actions to trigger on value change. Runtime payload automatically includes qty.',
    },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the counter wrapper' },
  ],
  examples: [
    '<Counter initial={1} min={1} max={10} onCounterChange={handleQuantityChange} />',
    '<Counter initial={5} min={0} max={100} style={{width: "150px"}} />',
    '<Counter min={0} max={999} onCounterChange={(value) => updateCartQuantity(itemId, value)} />',
    '<Counter initial={25} min={10} max={50} style={{fontSize: "18px"}} />',
    '<Counter initial={3} isDisabled={true} />',
  ],
};

const compositionTips: string[] = [
  'Use Counter for quantity selectors; enforce min to avoid zero/negative values.',
  'Clamp the value within [min, max] and disable decrement/increment at bounds.',
  'Debounce onCounterChange when updates trigger heavy recalculations or API calls.',
  'Place Counter next to Price to reflect total cost updates dynamically.',
  'Use keyboard support (arrow keys) and proper aria-labels for accessibility.',
  'Use Counter for quantity selectors in shopping carts with min={1} to prevent zero quantities.',
  'Apply Counter in settings panels for numeric preferences like font size or timeout values.',
  'Set Counter min={0} for optional quantities where zero is a valid selection.',
  'Use Counter onCounterChange to update state and trigger calculations like price totals.',
  'Apply Counter with max value based on inventory or availability for e-commerce.',
  'Combine Counter with Typography labels for clear context about what is being counted.',
  'Use Counter initial prop to set default values based on user preferences or previous selections.',
  'Apply Counter style prop to adjust width for different numeric ranges (narrow for 1-10, wider for 1-999).',
  'Set Counter in Card components with product information for organized product listings.',
  'Use Counter with disabled state based on product availability or user permissions.',
  'Apply Counter with FlexContainer for inline layouts with labels and units.',
  'Combine Counter with real-time validation showing warnings when approaching limits.',
  'Use Counter min and max dynamically based on business rules or user tier.',
  'Apply Counter in forms for numeric field input with better UX than text inputs.',
  'Set Counter with consistent styling across similar contexts for familiar interactions.',
  'Use Counter onCounterChange with debouncing for expensive operations like API calls.',
  'Apply Counter with localStorage to persist quantities across sessions.',
  'Combine Counter with InlineNotification for stock warnings or limit messages.',
  'Use Counter for pagination controls with min={1} and max={totalPages}.',
  'Apply Counter style with larger touch targets on mobile for better usability.',
  'Set Counter with keyboard support allowing arrow keys for increment/decrement.',
  'Use Counter in comparison tables for selecting quantities of different items.',
  'Apply Counter with animation for smooth value transitions.',
  'Combine Counter with price display updating in real-time as quantity changes.',
  'Use Counter for time inputs like hours or minutes with appropriate min/max.',
  'Apply Counter with visual feedback when reaching min or max limits.',
  'Set Counter in Modal dialogs for quantity selection before adding to cart.',
  'Use Counter with batch update support for multiple items simultaneously.',
  'Apply Counter with undo functionality for accidental value changes.',
  'Combine Counter with tooltips showing bulk discount tiers.',
];

export default { component, compositionTips };
