const component = {
  name: 'DragAndDropFiles',
  import: "import { DragAndDropFiles } from 'gd-design-library'",
  description:
    'File upload component with drag-and-drop functionality, providing visual feedback during drag operations and customizable drop zones for intuitive file uploading experiences.',
  a2uiName: 'drag-and-drop-files',
  category: 'Forms & Input',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~3KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'children',
      type: 'A2UIComponent[]',
      description: 'Components rendered inside the default drop-zone state.',
    },
    {
      name: 'dragOverChildren',
      type: 'A2UIComponent[]',
      description: 'Components rendered as the drag-over overlay while files are hovering over the drop zone.',
    },
    {
      name: 'actions',
      type: 'string[]',
      description:
        'Optional action IDs triggered when files are dropped. The renderer includes dropped file metadata in the action payload.',
    },
    {
      name: 'styling',
      type: 'object',
      description: 'Custom CSS properties for styling the drag-and-drop container.',
    },
  ],
  examples: [
    '<DragAndDropFiles onDrop={handleFileUpload} dragOverContent={<Typography>Drop files here</Typography>}>{uploadButton}</DragAndDropFiles>',
    '<DragAndDropFiles targetRef={dropZoneRef} onDrop={(files) => processFiles(files)} styles={{border: "2px dashed #ccc"}}><Icon name="upload" /><Typography>Drag files here or click to browse</Typography></DragAndDropFiles>',
    '<DragAndDropFiles onDragEnter={() => setIsDragging(true)} onDragLeave={() => setIsDragging(false)} onDrop={handleDrop}>{isDragging ? <Loader /> : <InputFile />}</DragAndDropFiles>',
    '<DragAndDropFiles triggerRef={buttonRef} targetRef={containerRef} dragOverContent={<Card isHighlighted><Typography>Release to upload</Typography></Card>}>{children}</DragAndDropFiles>',
  ],
};

const compositionTips: string[] = [
  'Visually highlight the drop zone on drag over to guide the user.',
  'Validate file types and sizes in onDrop before uploading.',
  'Provide keyboard-accessible alternatives to drag-and-drop for accessibility.',
  'Show progress indicators and error messages for upload status.',
  'Use DragAndDropFiles with targetRef pointing to a visually distinct drop zone container for clear interaction boundaries.',
  'Apply DragAndDropFiles dragOverContent with clear visual feedback like highlighted borders or overlay to indicate active drop zone.',
  'Set DragAndDropFiles onDrop handler with file validation logic checking file types, sizes, and counts before processing.',
  'Use DragAndDropFiles with Card component as wrapper providing bordered drop zone with padding for comfortable interaction area.',
  'Apply DragAndDropFiles styles with dashed border and subtle background color to indicate droppable area in default state.',
  'Combine DragAndDropFiles with InputFile as fallback for browsers that do not support drag and drop or for user preference.',
  'Use DragAndDropFiles onDragEnter and onDragLeave to manage visual state changes like border color or background highlights.',
  'Apply DragAndDropFiles dragOverContent with Icon and Typography showing "Drop files here" message for clear user guidance.',
  'Set DragAndDropFiles with InlineNotification after onDrop to show upload success, errors, or file validation messages.',
  'Use DragAndDropFiles targetRef with useRef hook to properly reference the drop zone DOM element for event handling.',
  'Apply DragAndDropFiles with multiple file support showing file count and list in dragOverContent for batch uploads.',
  'Combine DragAndDropFiles with ProgressBar component to show upload progress after files are dropped.',
  'Use DragAndDropFiles onDragOver with preventDefault() to enable drop functionality and prevent default browser behavior.',
  'Apply DragAndDropFiles with file type restrictions in onDrop handler matching accept attribute patterns from InputFile.',
  'Set DragAndDropFiles children with upload instructions, supported file types, and maximum file size information.',
  'Use DragAndDropFiles with triggerRef pointing to a button that opens file dialog as alternative to drag and drop.',
  'Apply DragAndDropFiles with visual transitions using CSS classes toggled by drag state for smooth user experience.',
  'Combine DragAndDropFiles with image preview generation showing thumbnails of dropped images before upload.',
  'Use DragAndDropFiles onDrop with FileReader API to read file contents for client-side processing or validation.',
  'Apply DragAndDropFiles with disabled state styling when uploads are in progress or quota is exceeded.',
  'Set DragAndDropFiles dragOverContent with Loader component when processing dropped files for immediate feedback.',
  'Use DragAndDropFiles with error boundary to gracefully handle drag and drop API failures in older browsers.',
  'Apply DragAndDropFiles styles with min-height to ensure adequate drop zone size even with minimal content.',
  'Combine DragAndDropFiles with file chunking logic in onDrop for large file upload optimization.',
  'Use DragAndDropFiles with keyboard accessibility providing alternative upload method via Space or Enter key.',
  'Apply DragAndDropFiles with mobile touch event fallbacks since drag and drop may not work on all mobile devices.',
  'Set DragAndDropFiles with clear visual distinction between drag-over and default states using contrasting colors.',
  'Use DragAndDropFiles onDrop with async/await pattern for sequential file processing with error handling.',
  'Apply DragAndDropFiles with maximum file count validation providing user feedback when limits are exceeded.',
  'Combine DragAndDropFiles with Modal for file upload confirmation or additional metadata input after drop.',
  'Use DragAndDropFiles dragOverContent with animation effects like pulse or glow to draw user attention.',
  'Apply DragAndDropFiles with consistent drop zone styling across the application for familiar interaction patterns.',
  'Set DragAndDropFiles with data transfer effectAllowed and dropEffect for proper drag operation feedback.',
  'Use DragAndDropFiles children with FlexContainer layout organizing upload icon, text, and button vertically.',
  'Apply DragAndDropFiles with file deduplication logic in onDrop preventing duplicate file uploads.',
  'Combine DragAndDropFiles with cloud storage service integration for direct-to-cloud uploads.',
  'Use DragAndDropFiles onDragEnter with file type checking to show early validation feedback during drag.',
  'Apply DragAndDropFiles with responsive design adjusting drop zone size and content based on viewport.',
  'Set DragAndDropFiles with ARIA attributes for screen reader announcements of drag and drop operations.',
  'Use DragAndDropFiles dragOverContent with percentage-based upload progress when processing multiple files.',
  'Apply DragAndDropFiles with cancel upload functionality allowing users to stop in-progress transfers.',
  'Combine DragAndDropFiles with compression utilities for automatic image optimization before upload.',
  'Use DragAndDropFiles styles with hover effects on desktop to indicate interactive drop zone area.',
  'Apply DragAndDropFiles with virus scanning integration for security validation of uploaded files.',
  'Set DragAndDropFiles with localStorage to persist upload history or resume interrupted uploads.',
  'Use DragAndDropFiles onDrop with metadata extraction reading EXIF data from images or document properties.',
  'Apply DragAndDropFiles with retry mechanism for failed uploads with exponential backoff strategy.',
  'Combine DragAndDropFiles with real-time collaboration features showing who is uploading files.',
  'Use DragAndDropFiles dragOverContent with file type icons indicating accepted formats visually.',
];

export default { component, compositionTips };
