const component = {
  name: 'Form',
  import: "import { Form } from 'gd-design-library'",
  description:
    'Semantic form wrapper component that handles form submission, field changes, and provides a structured container for form elements with built-in event handling.',
  a2uiName: 'form',
  category: 'Forms & Input',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~2KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'children',
      type: 'A2UIComponent[]',
      description: 'Form fields, buttons, and other form controls',
      required: true,
    },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the form (e.g. { maxWidth: "600px" })' },
    { name: 'actions', type: 'string[]', description: 'Action IDs from ui.actions to trigger on form submit' },
  ],
  examples: [
    '<Form onSubmit={handleSubmit}><Input name="email" type="email" required /><Button type="submit">Submit</Button></Form>',
    '<Form onChange={handleFieldChange} className="login-form"><Column gutter={16}>{formFields}</Column></Form>',
    '<Form onSubmit={handleFormSubmit} styles={{maxWidth: "400px"}}><Card padding="20px">{inputs}</Card></Form>',
  ],
};

const compositionTips: string[] = [
  'Use Form component as the semantic wrapper for all form elements instead of generic containers.',
  'Apply Form onSubmit handler with preventDefault to control submission programmatically.',
  'Set Form onChange handler to track field changes for real-time validation and auto-save.',
  'Combine Form with Column or FlexContainer inside for organized field layout.',
  'Use Form with InlineNotification at the top for submission success or error messages.',
  'Apply Form with sticky submit button on mobile for always-accessible submission.',
  'Use Form component as the semantic wrapper for all form elements instead of div or FlexContainer.',
  'Apply Form onSubmit handler with preventDefault to control form submission behavior programmatically.',
  'Set Form onChange handler to track field changes for real-time validation and auto-save features.',
  'Use Form with Card component wrapped inside for visually grouped form sections with borders.',
  'Apply Form styles={{maxWidth: "600px"}} to limit form width for better readability on large screens.',
  'Combine Form with Column or FlexContainer inside for organized field layout with proper spacing.',
  'Use Form className for applying consistent form styling across the application.',
  'Apply Form onSubmit with async handling for API calls, showing loading states during submission.',
  'Set Form onChange to enable/disable submit Button based on form validity.',
  'Use Form with nested Card components for multi-section forms like user profiles or settings.',
  'Apply Form with InlineNotification at the top for submission success or error messages.',
  'Combine Form with Input components using consistent naming for easy form data extraction.',
  'Use Form onSubmit to collect FormData and serialize for API submission.',
  'Apply Form with conditional rendering of fields based on other field values for dynamic forms.',
  'Set Form noValidate attribute via props to handle validation manually in JavaScript.',
  'Use Form with fieldset and legend elements inside for grouped related fields.',
  'Apply Form with disabled state on all child inputs during submission to prevent changes.',
  'Combine Form onChange with debouncing for performance optimization in large forms.',
  'Use Form with progressive disclosure pattern, showing additional fields as needed.',
  'Apply Form styles for responsive layout adjustments on mobile devices.',
  'Set Form with aria-label or aria-labelledby for accessibility when form purpose is not obvious.',
  'Use Form onSubmit validation with focus on first invalid field for better UX.',
  'Apply Form with Button type="submit" for proper form submission via Enter key.',
  'Combine Form with Button type="reset" for clearing all fields to defaults.',
  'Use Form onChange to update preview sections in real-time for WYSIWYG experiences.',
  'Apply Form with scroll to first error after validation failure for long forms.',
  'Set Form autocomplete attributes on child inputs for better browser integration.',
  'Use Form with step indicators or progress bars for multi-step form processes.',
  'Apply Form onSubmit with confirmation dialog for destructive or important actions.',
  'Combine Form with localStorage to persist draft data preventing data loss.',
  'Use Form with Input required props for HTML5 validation as fallback.',
  'Apply Form className with CSS Grid for complex multi-column layouts.',
  'Set Form with consistent spacing between field groups using Column gutter.',
  'Use Form onChange to calculate and display computed fields like totals or summaries.',
  'Apply Form with tooltip hints on complex fields for additional user guidance.',
  'Combine Form with keyboard navigation optimization using proper tabIndex ordering.',
  'Use Form onSubmit with redirect after successful submission to success page.',
  'Apply Form with error boundary to gracefully handle rendering errors.',
  'Set Form with print styles for forms that need to be printed or saved as PDF.',
  'Use Form onChange with field dependencies to enable/disable related fields.',
  'Apply Form with consistent error display pattern using InlineNotification below fields.',
  'Combine Form with Select, Input, and InputFile for comprehensive data collection.',
  'Use Form styles={{padding: "20px"}} for comfortable spacing around form content.',
  'Apply Form with sticky submit button on mobile for always-accessible submission.',
  'Set Form with data attributes for analytics tracking of form interactions.',
  'Use Form onSubmit with optimistic UI updates for better perceived performance.',
  'Apply Form with skeleton loading states while fetching initial form data.',
  'Combine Form with dirty state tracking to warn users about unsaved changes.',
  'Use Form className with theme-specific styling for dark/light mode support.',
];

export default { component, compositionTips };
