// Size px values mirror libs/ui/src/tokens/icon.ts — keep in sync when tokens change
const ICON_SIZE_PX: Record<string, number> = { xs: 14, sm: 16, md: 18, lg: 24, xl: 32, xxl: 40 };
const sizeDescription = Object.entries(ICON_SIZE_PX)
  .map(([key, px]) => `${key}=${px}`)
  .join(', ');

const component = {
  name: 'Icon',
  import: "import { Icon } from 'gd-design-library'",
  description:
    'SVG icon component that renders icons from a registered list with customizable size and color options. CRITICAL: Only use icon names from the availableIcons list. A2UI SPEC: set icon name in top-level "icon" field, "fill"/"fillSvg" as top-level fields (NOT inside "attributes", NOT inside "styling"). Example: {"type":"icon","icon":"star","size":"md","fill":"icon.primary"}.',
  a2uiName: 'icon',
  category: 'Content & Media',
  availableIcons: [
    'cross',
    'success',
    'error',
    'warning',
    'info',
    'dot',
    'check',
    'arrowDown',
    'arrowRight',
    'arrowLeft',
    'arrowForward',
    'keyboardArrowDown',
    'keyboardArrowUp',
    'mobileMenu',
    'home',
    'slash',
    'localShipping',
    'favorite',
    'favoriteOutlined',
    'shoppingBag',
    'paymentCard',
    'accountCircle',
    'portrait',
    'deleteOutlined',
    'minus',
    'plus',
    'edit',
    'search',
    'filter',
    'ruler',
    'attachment',
    'upload',
    'folder',
    'folderOpen',
    'contentCopy',
    'fileCopy',
    'eye',
    'volumeUp',
    'send',
    'chat',
    'chatBubble',
    'phone',
    'processing',
    'wifiTethering',
    'star',
    'starOutlined',
    'starHalf',
    'thumbUp',
    'thumbDown',
    'thumbUpFilled',
    'thumbDownFilled',
    'errorOutline',
    'mic',
  ],
  complexity: 'Low',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Lightweight',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~2KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'icon',
      type: 'string',
      description:
        'A2UI spec field for the icon name — MUST be from availableIcons. In A2UI JSON use top-level "icon" field: {"type":"icon","icon":"star"}. Do NOT use "label" or "attributes.name" for the icon name.',
      required: true,
    },
    {
      name: 'size',
      type: 'string',
      description: `Top-level size token. Resolves to fixed px dimensions: ${sizeDescription}. Overrides width/height when set.`,
      enum: ['xs', 'sm', 'md', 'lg', 'xl', 'xxl'] as const,
    },
    {
      name: 'width',
      type: 'number',
      description: 'Top-level custom width in pixels. Only used when size is not set. Example: 20.',
    },
    {
      name: 'height',
      type: 'number',
      description: 'Top-level custom height in pixels. Only used when size is not set. Example: 20.',
    },
    {
      name: 'fill',
      type: 'string',
      description:
        'Top-level A2UI field. Fill color for multi-path icons. Prefer theme color token paths (e.g. "icon.error", "icon.primary", "icon.default", "icon.success", "icon.info", "icon.warning", "icon.white", "icon.black"). Use raw CSS/hex only when no theme token fits. Do NOT put this inside "attributes" or "styling".',
    },
    {
      name: 'fillSvg',
      type: 'string',
      description:
        'Top-level A2UI field. Uniform fill color for the entire SVG. Prefer theme color token paths (same options as fill). Use raw CSS/hex only when no theme token fits. Use when you want one single color across the whole icon. Do NOT put this inside "attributes" or "styling".',
    },
    {
      name: 'ariaLabel',
      type: 'string',
      description: 'Accessible label for meaningful or interactive standalone icons.',
    },
    { name: 'actions', type: 'string[]', description: 'Action IDs from ui.actions to trigger on click.' },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the icon' },
  ],
  examples: [
    '<Icon name="search" size="md" />',
    '<Icon name="cross" width={24} height={24} fill="icon.error" />',
    '<Icon name="arrowRight" fillSvg="currentColor" />',
    '<Icon name="edit" size="lg" fill="icon.primary" />',
    '<Icon name="check" size="md" fill="icon.success" />',
    '<Icon name="info" size="md" fill="icon.info" />',
    '<Icon name="warning" size="md" fill="icon.warning" />',
    '<Icon name="chat" size="md" fill="icon.default" />',
    '<Icon name="chatBubble" size="sm" fillSvg="currentColor" />',
    '<Icon name="phone" size="lg" fill="icon.info" />',
    '<Icon name="thumbUp" size="md" />',
    '<Icon name="star" size="sm" fill="icon.primary" />',
    '<Icon name="check" size="md" margin="8px" padding="4px" />',
    '<Icon name="search" size="lg" position="absolute" top="10px" right="10px" />',
    '<Icon name="edit" size="sm" marginRight="12px" />',
  ],
  iconCatalog: {
    'Status & Feedback': {
      cross: 'Close or cancel actions, dismiss modals, remove items',
      success: 'Success states, completed actions, positive feedback',
      error: 'Error states, failed actions, critical issues',
      warning: 'Warning states, caution messages, attention needed',
      info: 'Information states, helpful tips, general notifications',
      dot: 'List items, pagination, status indicators',
      check: 'Completed tasks, verified items, confirmation states',
      errorOutline: 'Error indicators, warning outlines',
    },
    'Navigation & Direction': {
      arrowDown: 'Dropdown indicators, expand content, scroll down',
      arrowRight: 'Next page, continue, forward navigation',
      arrowLeft: 'Previous page, back navigation, return',
      arrowForward: 'Send, submit, proceed to next step',
      keyboardArrowDown: 'Collapse content, dropdown menus',
      keyboardArrowUp: 'Expand content, scroll to top',
    },
    'UI & Interface': {
      mobileMenu: 'Mobile navigation menu, hamburger menu',
      home: 'Home page, main dashboard, primary navigation',
      slash: 'Separators, dividers, breadcrumb separators',
    },
    'E-commerce & Shopping': {
      localShipping: 'Shipping, delivery, logistics',
      favorite: 'Favorited items, liked content (filled)',
      favoriteOutlined: 'Add to favorites, like content (outline)',
      shoppingBag: 'Shopping cart, e-commerce, purchases',
      paymentCard: 'Payment methods, credit cards, billing',
    },
    'User & Account': {
      accountCircle: 'User profile, account settings, avatar',
      portrait: 'User photo, profile picture, avatar',
    },
    'Actions & Operations': {
      deleteOutlined: 'Delete items, remove content, trash',
      minus: 'Decrease quantity, remove items, collapse',
      plus: 'Add items, increase quantity, expand',
      edit: 'Edit content, modify items, pencil action',
      search: 'Search functionality, find content',
      filter: 'Filter options, sort content, refine results',
      ruler: 'Measurements, dimensions, sizing tools',
    },
    'File & Document': {
      attachment: 'File attachments, document links',
      upload: 'Upload files, import content, add media',
      folder: 'Closed folders, directory structure',
      folderOpen: 'Open folders, expanded directories',
      contentCopy: 'Copy content, duplicate text',
      fileCopy: 'Copy files, duplicate documents',
    },
    'Media & Communication': {
      eye: 'View content, visibility toggle, preview',
      volumeUp: 'Audio controls, sound settings, volume',
      send: 'Send messages, submit forms, transmit',
      mic: 'Voice recording, microphone input, audio capture',
      chat: 'General chat, messaging functionality',
      chatBubble: 'Individual messages, conversation threads',
      phone: 'Contact, calling, communication features',
    },
    'System & Technical': {
      processing: 'Loading states, processing operations',
      wifiTethering: 'Network connection, wireless settings',
    },
    'Rating & Feedback': {
      star: 'Filled star ratings, favorited items',
      starOutlined: 'Empty star ratings, rate items',
      starHalf: 'Half star ratings, partial scores',
      thumbUp: 'Like, approve, positive feedback (outline)',
      thumbDown: 'Dislike, disapprove, negative feedback (outline)',
      thumbUpFilled: 'Liked, approved, positive feedback (filled)',
      thumbDownFilled: 'Disliked, disapproved, negative feedback (filled)',
    },
  },
};

const compositionTips: string[] = [
  'Use top-level icon with names from the shared icon catalog, and omit the icon when no listed name fits.',
  'Use size for standard sizing and width or height only when you need an exact pixel override.',
  'Use fill or fillSvg as top-level color fields instead of hiding icon color inside attributes or styling.',
  'Use actions[] for interactive icons, and add ariaLabel when the icon alone carries meaning.',
  'Use styling for spacing or positioning around the icon without changing the icon name or color contract.',
];

export default { component, compositionTips };
