const component = {
  name: 'InlineNotification',
  import: "import { InlineNotification } from 'gd-design-library'",
  description:
    'Inline notification component for displaying contextual messages, alerts, and feedback with different severity levels.',
  a2uiName: 'inline-notification',
  category: 'Feedback & Status',
  complexity: 'Low',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Lightweight',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~1KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'variant',
      type: 'string',
      description: 'Visual severity variant of the notification',
      enum: ['info', 'warning', 'error', 'success', 'basic'] as const,
      default: 'info',
    },
    { name: 'label', type: 'string', description: 'Optional emphasized heading shown at the top of the notification' },
    { name: 'value', type: 'string', description: 'Primary body message shown inside the notification' },
    {
      name: 'children',
      type: 'A2UIComponent[]',
      description: 'Optional nested components rendered below the text for richer notification content',
    },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the notification' },
  ],
  examples: [
    '<InlineNotification variant="success">Your changes have been saved successfully.</InlineNotification>',
    '<InlineNotification variant="error">Failed to process request. Please try again.</InlineNotification>',
    '<InlineNotification variant="warning">This action cannot be undone.</InlineNotification>',
    '<InlineNotification variant="info">New features are available in settings.</InlineNotification>',
  ],
};

const compositionTips: string[] = [
  'Use InlineNotification variant="error" for form validation errors and critical alerts.',
  'Apply InlineNotification variant="success" after successful form submissions or actions.',
  'Use InlineNotification variant="warning" for cautionary messages before destructive actions.',
  'Apply InlineNotification variant="info" for neutral informational messages and tips.',
  'Place InlineNotification above or below form fields for contextual validation messages.',
  'Combine InlineNotification with Icon components in children for enhanced visual communication.',
  'Use InlineNotification variant="error" for form validation errors and critical alerts.',
  'Apply InlineNotification variant="success" after successful form submissions or actions.',
  'Use InlineNotification variant="warning" for cautionary messages before destructive actions.',
  'Apply InlineNotification variant="info" for neutral informational messages and tips.',
  'Place InlineNotification above form fields for field-specific validation messages.',
  'Use InlineNotification at the top of forms for general submission feedback.',
  'Combine InlineNotification with Icon components in children for enhanced visual communication.',
  'Apply InlineNotification with dismissible button using children prop for closeable alerts.',
  'Use InlineNotification variant="error" with detailed error messages from API responses.',
  'Position InlineNotification below Input fields for inline validation feedback.',
  'Apply InlineNotification with consistent spacing using margin/padding in containers.',
  'Use InlineNotification with fade-in animations for smooth appearance on state changes.',
  'Combine InlineNotification with conditional rendering based on form validation state.',
  'Apply InlineNotification variant="info" for helper text that appears on user interaction.',
  'Use InlineNotification in Card components for section-specific alerts and messages.',
  'Set InlineNotification with Typography children for rich text formatting in messages.',
  'Apply InlineNotification with auto-dismiss timer for temporary success messages.',
  'Use InlineNotification variant="warning" before form submission for incomplete fields.',
  'Combine InlineNotification with Link components in children for actionable messages.',
  'Apply InlineNotification consistently across similar UI contexts for unified experience.',
  'Use InlineNotification with role="alert" for important messages requiring immediate attention.',
  'Position InlineNotification at viewport top for global application messages.',
  'Apply InlineNotification with list formatting in children for multiple error messages.',
  'Use InlineNotification variant transitions when severity changes based on user actions.',
  'Combine InlineNotification with form field highlighting for better error visibility.',
  'Apply InlineNotification with compact styling in dense UI layouts.',
  'Use InlineNotification for real-time validation feedback as users type.',
  'Set InlineNotification with appropriate contrast ratios for accessibility.',
  'Apply InlineNotification with consistent icon usage per variant for quick recognition.',
  'Use InlineNotification in modal dialogs for action confirmations and warnings.',
  'Combine InlineNotification with progress indicators for long-running operations.',
  'Apply InlineNotification variant="success" with next-step guidance after actions.',
  'Use InlineNotification for connection status and network error messages.',
  'Position InlineNotification strategically to avoid covering important UI elements.',
  'Apply InlineNotification with responsive design adapting message length on mobile.',
  'Use InlineNotification children with Button components for inline actions.',
  'Combine InlineNotification with data attributes for analytics tracking.',
  'Apply InlineNotification with consistent timing for auto-dismiss across the app.',
  'Use InlineNotification variant="error" with retry actions for failed operations.',
  'Set InlineNotification with clear, actionable language avoiding technical jargon.',
  'Apply InlineNotification sparingly to avoid notification fatigue.',
  'Use InlineNotification with keyboard accessibility for screen reader users.',
  'Combine InlineNotification with sound/vibration for critical alerts on mobile.',
  'Apply InlineNotification with print styles for important messages in printed documents.',
];

export default { component, compositionTips };
