const component = {
  name: 'Input',
  import: "import { Input } from 'gd-design-library'",
  description:
    'Versatile form input component supporting multiple field types including text, email, password, checkbox, radio, and more. Includes built-in label, helper text, and adornment support.',
  a2uiName: 'input',
  category: 'Forms & Input',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~3KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    { name: 'label', type: 'string', description: 'Input label text displayed above the field' },
    { name: 'placeholder', type: 'string', description: 'Placeholder text shown when input is empty' },
    { name: 'value', type: 'string', description: 'Controlled value of the input' },
    {
      name: 'variant',
      type: 'string',
      description: 'Input field type variant',
      enum: [
        'text',
        'email',
        'password',
        'number',
        'tel',
        'url',
        'search',
        'radio',
        'checkbox',
        'date',
        'time',
        'month',
        'week',
        'color',
        'range',
      ] as const,
    },
    { name: 'required', type: 'boolean', description: 'Whether the input is required for form validation' },
    { name: 'disabled', type: 'boolean', description: 'Whether the input is disabled' },
    { name: 'readOnly', type: 'boolean', description: 'Whether the input is read-only' },
    {
      name: 'helpText',
      type: 'string',
      description: 'Helper text shown below the field (e.g. format hints, validation messages)',
    },
    {
      name: 'color',
      type: 'string',
      description: 'Color state for validation feedback',
      enum: ['primary', 'error', 'success', 'warning'] as const,
    },
    {
      name: 'icon',
      type: 'string',
      description: 'Leading adornment icon name from the shared A2UI icon catalog.',
    },
    {
      name: 'iconEnd',
      type: 'string',
      description: 'Trailing adornment icon name from the shared A2UI icon catalog.',
    },
    { name: 'name', type: 'string', description: 'HTML name attribute for form data submission' },
    {
      name: 'debounceCallbackTime',
      type: 'number',
      description: 'Delay in ms before onChange fires (useful for search/auto-save)',
    },
    {
      name: 'ariaDescribedBy',
      type: 'string',
      description: 'ID of helper or error text associated with the input for screen readers.',
    },
    {
      name: 'checked',
      type: 'boolean',
      description: 'Checked state for checkbox and radio variants. Use with variant="checkbox" or variant="radio".',
    },
    {
      name: 'indeterminate',
      type: 'boolean',
      description: 'Indeterminate (mixed) state for variant="checkbox". Use for partial-selection controls.',
    },
    { name: 'actions', type: 'string[]', description: 'Action IDs from ui.actions to trigger on value change.' },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the input' },
  ],
  examples: [
    '<Input variant={InputVariantType.Email} label="Email Address" placeholder="user@example.com" required />',
    '<Input variant={InputVariantType.Password} label="Password" helperText="Must be at least 8 characters" />',
    '<Input variant={InputVariantType.Text} adornmentStart={<Icon name="search" />} placeholder="Search..." />',
    '<Input variant={InputVariantType.Checkbox} label="Remember me" checked={isChecked} onChange={handleChange} />',
    '<Input variant={InputVariantType.Checkbox} label="Select all" indeterminate={hasPartial} checked={allSelected} onChange={handleSelectAll} />',
  ],
};

const compositionTips: string[] = [
  'Use label for the visible field label and helpText for supporting guidance or validation copy.',
  'Use icon and iconEnd for lightweight start/end adornments instead of React nodes.',
  'Use debounceCallbackTime when the input should avoid firing change actions on every keystroke.',
  'Use ariaDescribedBy when external helper or error text should be announced by screen readers.',
  'Wire input updates through actions[] instead of raw onChange callbacks.',
  'For checkbox inputs in A2UI, use variant="checkbox" with checked and indeterminate props. NEVER emit { type: "checkbox" }.',
];

export default { component, compositionTips };
