const component = {
  name: 'List',
  import: "import { List } from 'gd-design-library'",
  description:
    'Flexible list component for displaying collections of items with various style variants including unordered, ordered, and inline layouts.',
  a2uiName: 'list',
  category: 'Content & Structure',
  complexity: 'Low',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Lightweight',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~1KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'options',
      type: 'Array<{ label: string; value?: string | number; icon?: string }>',
      description: 'Preferred list item source for simple text or icon-backed list rows',
    },
    {
      name: 'value',
      type: 'Array<string | number | { label?: string; name?: string; title?: string; description?: string }>',
      description: 'Fallback array source for primitive or lightweight object list items',
    },
    {
      name: 'variant',
      type: 'string',
      description: 'List style variant controlling bullet/numbering style',
      enum: ['ordered-circle', 'ordered-square', 'unordered-dot', 'unordered-check'] as const,
    },
    {
      name: 'size',
      type: 'string',
      description: 'Size of the list items',
      enum: ['sm', 'md'] as const,
    },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the list' },
  ],
  examples: [
    '<List variant="unordered-dot" items={["First item", "Second item", "Third item"]} />',
    '<List variant="unordered-check" items={features} />',
    '<List variant="ordered-circle" items={steps.map(step => <Typography>{step}</Typography>)} />',
    '<List variant="ordered-square" items={steps} size="sm" />',
    '<List items={features.map(f => <FlexContainer gap="8px"><Icon name={f.icon} /><Typography>{f.text}</Typography></FlexContainer>)} />',
  ],
};

const compositionTips: string[] = [
  'Use List variant="unordered-dot" for bullet lists and variant="ordered-circle" for step-by-step instructions.',
  'Use List variant="unordered-check" for feature or benefit checklists.',
  'Use List variant="ordered-square" for alternative numbered list styles.',
  'Combine List items with Icon + Typography for richer visual lists.',
  'Use className to apply custom bullets, counters, or spacing utilities.',
  'Wrap long lists in Scroll to constrain height while keeping headers visible.',
  'Keep list item content consistent in height for clean vertical rhythm.',

  'Use List variant="unordered-dot" for feature lists, benefits, or any non-sequential information.',
  'Use List variant="unordered-check" for confirming features, steps completed, or included capabilities.',
  'Apply List variant="ordered-circle" for step-by-step instructions, rankings, or sequential processes.',
  'Use List items with Typography components for consistent text styling across list items.',
  'Apply List with Icon components in items for visual list markers or category indicators.',
  'Combine List items with FlexContainer for complex list item layouts with icons and text.',
  'Use List className for applying consistent list styling patterns across the application.',
  'Set List styling prop for one-off customizations like spacing, colors, or typography.',
  'Use List variant="ordered-circle" with custom bullet styles via CSS for branded list markers.',
  'Combine List with Card component for organized content sections with listed information.',
  'Apply List items with Link components for navigation menus or resource lists.',
  'Set List with nested List components in items for multi-level hierarchical lists.',
  'Apply List items with conditional rendering for dynamic list content based on state.',
  'Use List with consistent spacing between items using styles or CSS for visual rhythm.',
  'Combine List variant="unordered-dot" with InlineNotification items for error or warning lists.',
  'Apply List items with Button components for action lists or interactive menus.',
  'Use List variant="ordered-circle" for form validation error lists with numbered issues.',
  'Set List items with Badge components for status indicators or counts in list items.',
  'Apply List with Column wrapper for proper vertical spacing from surrounding content.',
  'Combine List items with Checkbox inputs for multi-select lists or todo lists.',
  'Apply List with empty state message when items array is empty for better UX.',
  'Use List items with truncation styles for long text in constrained layouts.',
  'Set List variant based on semantic meaning: ordered-circle/ordered-square for sequences, unordered-dot/unordered-check for collections.',
  'Apply List with hover states on items for interactive list experiences.',
  'Use List items with React.Fragment for multiple elements per list item without wrapper.',
  'Combine List with filter/search functionality for long searchable lists.',
  'Use List with virtualization for performance optimization with thousands of items.',
  'Set List items with key props for efficient React rendering and updates.',
  'Apply List with drag-and-drop functionality for reorderable lists.',
  'Use List variant="unordered-dot" with indentation for sub-items in tree structures.',
  'Combine List with accordion pattern for collapsible list sections.',
  'Apply List items with loading skeletons while fetching dynamic content.',
  'Use List with pagination or infinite scroll for large datasets.',
  'Set List className with print styles for proper list formatting in printed documents.',
  'Apply List with ARIA attributes for improved screen reader accessibility.',
  'Use List items with timestamps or metadata using Typography variant="caption" as="div".',
  'Combine List with sorting functionality for user-controlled list ordering.',
  'Apply List variant="ordered-circle" with reverse styles for countdown lists.',
  'Use List with consistent icon sizing in items for visual alignment.',
  'Set List items with alternating background colors for improved readability.',
  'Apply List with keyboard navigation support for accessible list interactions.',
  'Combine List with expand/collapse controls for detailed list items.',
  'Apply List items with progress indicators for task or process lists.',
  'Use List with data attributes for analytics tracking of list interactions.',
];

export default { component, compositionTips };
