const component = {
  name: 'Menu',
  import: "import { Menu, MenuRef } from 'gd-design-library'",
  description:
    'Flexible dropdown menu component with smart positioning, customizable behavior, public API via ref, and full Box layout support.',
  a2uiName: 'menu',
  category: 'Navigation & Structure',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~2KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    { name: 'label', type: 'string', description: 'Text displayed in the trigger button', required: true },
    { name: 'icon', type: 'string', description: 'Optional leading icon for the trigger button' },
    { name: 'iconEnd', type: 'string', description: 'Optional trailing icon for the trigger button' },
    { name: 'variant', type: 'string', description: 'Trigger button variant (for example "text" or "secondary")' },
    {
      name: 'options',
      type: 'Array<{ value: string | number; label: string; disabled?: boolean; href?: string }>',
      description: 'Menu item definitions rendered inside the dropdown',
      required: true,
    },
    {
      name: 'placement',
      type: 'string',
      description: 'Position of the dropdown relative to the trigger',
      enum: ['top-left', 'top-right', 'bottom-left', 'bottom-right'] as const,
      default: 'bottom-right',
    },
    {
      name: 'closeOnSelect',
      type: 'boolean',
      description: 'Whether the menu closes after an item is selected',
      default: true,
    },
    { name: 'offsetX', type: 'number', description: 'Horizontal pixel offset between menu and trigger', default: 4 },
    { name: 'offsetY', type: 'number', description: 'Vertical pixel offset between menu and trigger', default: 4 },
    {
      name: 'minHeight',
      type: 'number',
      description: 'Minimum height constraint for dynamic height calculation',
      default: 80,
    },
    {
      name: 'maxHeight',
      type: 'number',
      description: 'Maximum height constraint for dynamic height calculation',
      default: 400,
    },
    {
      name: 'actions',
      type: 'string[]',
      description: 'Action IDs from ui.actions to trigger when a menu item is selected',
    },
    { name: 'disabled', type: 'boolean', description: 'Disables the trigger button when true' },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the menu container' },
  ],
  examples: [
    '<Menu content={<DropdownItem name="Profile" value="profile" />} onSelect={(props) => console.log(props.data)}>Menu</Menu>',
    '<Menu closeOnSelect={false} content={menuItems} onSelect={handleSelect}>Open Menu</Menu>',
    '<Menu ref={menuRef} content={items}><Button>Menu</Button></Menu>',
    '<Menu placement="top-left" content={menuItems}>Menu (Top Left)</Menu>',
    '<Menu placement="bottom-right" content={menuItems}>Menu (Bottom Right - Default)</Menu>',
    '<Menu offsetX={8} offsetY={8} minHeight={100} maxHeight={500} content={menuItems}>Menu with positioning options</Menu>',
    '<Menu padding="16px" marginTop="8px" content={menuItems}>Menu with spacing</Menu>',
    '<Menu width="200px" maxHeight={300} overflow="auto" content={menuItems}>Menu with dimensions</Menu>',
  ],
};

const compositionTips: string[] = [
  'Use Menu for dropdown menus with selectable options, typically containing DropdownItem components.',
  'Set Menu closeOnSelect={false} to keep the menu open after selecting items, useful for multi-select scenarios.',
  'Use Menu ref API (ref.open(event.target), ref.close(event.target)) for programmatic control of menu state. Pass event.target as the parameter to identify API-controlled interactions, which helps distinguish programmatic control from user interactions.',
  'Menu positioning algorithm uses viewport-based calculations with scroll-aware conversion to document coordinates for accurate absolute positioning in Portal.',
  'Use Menu children prop for custom trigger elements - can be a Button, Icon, Text, or any clickable element.',
  'Menu content prop accepts any ReactNode, but typically contains DropdownItem components for selectable options.',
  'Menu ref provides access to current state: ref.isOpen, ref.selectedValue, and control methods: ref.open(target?), ref.close(target?). Pass event.target when calling from event handlers to identify API-controlled interactions.',
  'Menu onSelect callback receives { event, data } where data contains { name, value } of the selected item.',
  'Use Menu itemIdentifier prop to customize how menu items are compared for selection tracking.',
  'Menu supports keyboard navigation - Escape key closes the menu.',
  'Menu automatically closes on click outside (mousedown event).',
  'Use Menu placement prop to explicitly set menu position relative to trigger: "top-left", "top-right", "bottom-left", or "bottom-right". Defaults to "bottom-right" if not specified.',
  'Set Menu placement="top-left" to show menu above and aligned to the left edge of the trigger, placement="top-right" for above and right-aligned, placement="bottom-left" for below and left-aligned, or placement="bottom-right" for below and right-aligned (default).',
  'Menu placement provides accurate corner positioning aligned to trigger edges for precise menu placement.',
  'Use Menu offsetX and offsetY props to control the horizontal and vertical distance in pixels between the menu and trigger element. Defaults are 4 pixels for both. Use offsetX for horizontal spacing and offsetY for vertical spacing.',
  'Set Menu minHeight and maxHeight props to control the height constraints for dynamic height calculations based on available viewport space. Defaults are 80px and 400px respectively.',
  'Menu uses minHeight and maxHeight for dynamic height calculations - the menu will adjust its height based on available viewport space, respecting these constraints.',
  'Menu supports full Box component props for flexible layout control - use margin, padding, position, flex, gap, and more for precise positioning and spacing.',
  'Set Menu width and height for exact dimensions, or use minWidth and maxWidth for width constraints. Use Menu-specific minHeight and maxHeight props for dynamic height calculations based on viewport space.',
  'Apply Menu margin for external spacing between menu container and other elements.',
  'Use Menu padding for internal spacing within the menu dropdown container.',
  'Set Menu position, top, right, bottom, left for precise positioning control.',
  'Use Menu display, flexDirection, justifyContent, alignItems for flexible layout control.',
  'Apply Menu zIndex to control stacking order when menus overlap.',
  'Set Menu overflow="auto" with maxHeight for scrollable menu content.',
];

export default { component, compositionTips };
