const component = {
  name: 'Modal',
  import: "import { Modal } from 'gd-design-library'",
  description:
    'Overlay dialog component for displaying content in a layer above the main application, with built-in backdrop, close controls, and accessibility features for focused user interactions.',
  a2uiName: 'modal',
  category: 'Overlay & Dialog',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~3KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'label',
      type: 'string',
      description:
        'Modal heading text rendered in the header area. Use title only when a separate metadata field is required.',
    },
    { name: 'title', type: 'string', description: 'Optional alternate heading text used for the modal header.' },
    { name: 'footer', type: 'A2UIComponent[]', description: 'Components rendered in the modal footer area.' },
    { name: 'children', type: 'A2UIComponent[]', description: 'Components rendered in the modal body.' },
    {
      name: 'showCloseButton',
      type: 'boolean',
      description: 'Whether to show the × close button in the header',
      default: true,
    },
    { name: 'closeOnEscape', type: 'boolean', description: 'Whether pressing Escape closes the modal', default: true },
    {
      name: 'closeOnClickOutside',
      type: 'boolean',
      description: 'Whether clicking the backdrop closes the modal',
      default: true,
    },
    {
      name: 'isCustomView',
      type: 'boolean',
      description: 'When true, suppresses default header/footer rendering for fully custom layouts',
    },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the modal container' },
  ],
  examples: [
    '<Modal isOpen={isOpen} onClose={handleClose} title="Confirm Action" footer={<Button onClick={handleConfirm}>Confirm</Button>}>Are you sure you want to proceed?</Modal>',
    '<Modal isOpen={showModal} onClose={() => setShowModal(false)} showCloseButton={false} closeOnEscape={false}><Form onSubmit={handleSubmit}>{formFields}</Form></Modal>',
    '<Modal isOpen={dialogOpen} onClose={closeDialog} title={<Typography variant="h3">Settings</Typography>} styles={{maxWidth: "600px"}}>{settingsContent}</Modal>',
    '<Modal isOpen={alertOpen} onClose={handleAlertClose} footer={<FlexContainer gap="8px" justifyContent="flex-end"><Button variant="text" onClick={handleCancel}>Cancel</Button><Button variant="contained" onClick={handleOk}>OK</Button></FlexContainer>}>{alertMessage}</Modal>',
    '<Modal isOpen={criticalModal} onClose={handleClose} closeOnClickOutside={false} title="Critical Action">This modal requires explicit confirmation and cannot be closed by clicking outside.</Modal>',
  ],
};

const compositionTips: string[] = [
  'Open Modal only when necessary to focus user attention on an action or message.',
  'Provide a clear onClose handler and ensure Escape/backdrop click behaviors match expectations.',
  'Keep content concise; move lengthy content into scrollable sections within the Modal.',
  'Use title and footer actions for clear context and decision points.',
  'Use Modal isOpen with state management (useState) to control modal visibility programmatically.',
  'Apply Modal onClose callback to update state and perform cleanup when modal is dismissed.',
  'Set Modal title with Typography component for consistent heading styles across all modals.',
  'Use Modal footer with FlexContainer to organize action buttons with proper spacing and alignment.',
  'Apply Modal showCloseButton={false} for critical actions that require explicit user choice.',
  'Set Modal closeOnEscape={false} when modal contains forms to prevent accidental data loss.',
  'Set Modal closeOnClickOutside={false} for critical actions that require explicit confirmation before closing.',
  'Use Modal closeOnClickOutside={false} with closeOnEscape={false} for forms to prevent accidental data loss.',
  'Use Modal with Form component in children for structured data collection in overlay context.',
  'Apply Modal styles={{maxWidth: "500px"}} to control modal width for optimal content display.',
  'Combine Modal with InlineNotification in children for validation messages or alerts.',
  'Use Modal footer with primary and secondary Button variants for clear action hierarchy.',
  'Set Modal with loading state in footer buttons during async operations.',
  'Apply Modal with Card component in children for visually grouped content sections.',
  'Use Modal title as string for simple headers or ReactNode for complex header layouts.',
  'Apply Modal with overflow scrolling in children for long content that exceeds viewport.',
  'Set Modal with stepped content using state to create multi-step wizards or processes.',
  'Use Modal onClose to trigger confirmation dialog for unsaved changes before closing.',
  'Apply Modal with keyboard focus management to trap focus within modal when open.',
  'Combine Modal with backdrop click handling via onClose for intuitive dismissal.',
  'Use Modal footer with Button fullWidth on mobile for better touch targets.',
  'Set Modal with animation classes in styles for smooth open/close transitions.',
  'Apply Modal with z-index management to ensure proper stacking above other content.',
  'Use Modal for confirmation dialogs with clear title and action buttons in footer.',
  'Apply Modal with responsive styles adapting to mobile viewport constraints.',
  'Set Modal with aria-label and role attributes for accessibility compliance.',
  'Use Modal children with Column or FlexContainer for organized content layout.',
  'Apply Modal with consistent padding in children for comfortable content spacing.',
  'Combine Modal with Select or Input components for filter or search interfaces.',
  'Use Modal isOpen with useEffect for side effects when modal opens or closes.',
  'Apply Modal with portal rendering to escape parent container constraints.',
  'Set Modal with prevent scroll on body when open to avoid background scrolling.',
  'Use Modal footer with disabled buttons based on form validation state.',
  'Apply Modal with custom close icon using showCloseButton and custom header.',
  'Combine Modal with ChatContainer for overlay chat widgets or help systems.',
  'Use Modal styles for custom positioning like slide-in from sides or bottom.',
  'Apply Modal with nested modals carefully, managing z-index and focus properly.',
  'Set Modal with data attributes for analytics tracking of modal interactions.',
  'Use Modal onClose with router navigation for modal routes in SPAs.',
  'Apply Modal with consistent sizing across similar modal types for UX coherence.',
  'Combine Modal with Image gallery for lightbox-style image viewing.',
  'Use Modal with video players ensuring proper cleanup on close.',
  'Apply Modal with print styles for printable modal content like receipts.',
  'Set Modal with autofocus on first interactive element for keyboard accessibility.',
  'Use Modal footer with tertiary actions using Link component for less prominent options.',
  'Apply Modal with error boundaries to handle and display errors gracefully.',
  'Combine Modal with real-time updates using websockets for live content.',
  'Use Modal with minimize/maximize controls for complex workspace interfaces.',
  'Apply Modal with drag handle for repositionable modal windows.',
  'Set Modal with size variants (small, medium, large) using consistent styles.',
  'Use Modal isOpen={false} by default to prevent flash of modal on initial render.',
];

export default { component, compositionTips };
