const component = {
  name: 'Portal',
  import: "import { Portal } from 'gd-design-library'",
  a2uiName: 'portal',
  description:
    'Utility component that renders its children into a different part of the DOM tree, useful for modals, tooltips, and overlays that need to escape parent container constraints while maintaining React component hierarchy.',
  category: 'Overlay & Dialog',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~2KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'blocksScroll',
      type: 'boolean',
      description: 'Whether to prevent scrolling of the underlying content when portal is open',
      default: false,
    },
    {
      name: 'container',
      type: 'string',
      description: 'Optional CSS selector for the portal target container. Omit to render into document.body.',
      default: 'document.body',
    },
    {
      name: 'withWrapper',
      type: 'boolean',
      description: 'Whether to wrap the portal content in a container element',
      default: true,
    },
    {
      name: 'wrapperVariant',
      type: 'string',
      description: 'The style variant for the wrapper container',
      default: 'fullPage',
      enum: ['inline', 'section', 'fullPage'] as const,
    },
    {
      name: 'WrapperView',
      type: 'string',
      description: 'Underlying HTML element to use for the optional wrapper, such as "div", "section", or "aside"',
      default: 'div',
    },
    {
      name: 'children',
      type: 'A2UIComponent[]',
      description: 'Nested A2UI child components rendered inside the portal',
      required: true,
    },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the portal container' },
  ],
  examples: [
    '<Portal blocksScroll={true}><Modal isOpen={true} onClose={handleClose}>{modalContent}</Modal></Portal>',
    '<Portal container="#tooltip-root" withWrapper={true} wrapperVariant="section"><Tooltip>{tooltipText}</Tooltip></Portal>',
    '<Portal withWrapper={true} wrapperVariant="fullPage" styling={{zIndex: 9999}}><NotificationToast /></Portal>',
    '<Portal blocksScroll={false} container="#sidebar-root"><NavigationMenu /></Portal>',
  ],
};

const compositionTips: string[] = [
  'Use Portal to render overlays above complex layout stacking contexts.',
  'Enable blocksScroll to prevent background scrolling when overlays are open.',
  'In A2UI JSON, container should be a CSS selector string that resolves to an existing DOM node.',
  'Choose wrapperVariant based on the available wrapper presets: inline, section, or fullPage.',
  'Set a specific container selector to scope the overlay to a subsection of the app.',
  'Use Portal for rendering content outside the normal DOM hierarchy to escape overflow hidden or z-index constraints.',
  'Apply Portal blocksScroll={true} when displaying modals or overlays to prevent background scrolling.',
  'Set Portal container to a specific selector for targeted rendering instead of document.body.',
  'Use Portal withWrapper={true} to add a wrapper element around portal content for styling control.',
  'Apply Portal wrapperVariant="fullPage" for full-screen overlays and "section" for scoped portal containers.',
  'Combine Portal with Modal for proper modal rendering that escapes parent constraints.',
  'Use Portal WrapperView="div" or another semantic tag when the helper wrapper should have a specific HTML element.',
  'Apply Portal styling for positioning and z-index management of overlay content.',
  'Set Portal blocksScroll={false} for non-blocking overlays like tooltips or popovers.',
  'Use Portal with conditional rendering to mount/unmount portal content based on state.',
  'Apply Portal container="#id" for rendering in specific page sections from A2UI JSON.',
  'Combine Portal with multiple children for complex overlay compositions.',
  'Use Portal wrapperVariant="fullPage" for full-screen takeover interfaces.',
  'Set Portal withWrapper={false} when children already have appropriate wrapper elements.',
  'Use Portal for dropdown menus that need to escape overflow hidden containers.',
  'Apply Portal with high z-index values in styling for proper stacking context.',
  'Use Portal for toast notifications that float above all content.',
  'Set Portal container dynamically based on responsive breakpoints or user preferences.',
  'Use Portal for context menus that appear at cursor position.',
  'Use Portal wrapperVariant="inline" for inline overlays within text content.',
  'Use Portal for floating action buttons that need consistent positioning.',
  'Use Portal for autocomplete dropdowns that need to escape container bounds.',
  'Apply Portal styling with CSS variables for theme-aware overlay styling.',
  'Use Portal for tour highlights that overlay specific page elements.',
  'Use Portal for video players that can go fullscreen or picture-in-picture.',
  'Set Portal container based on feature flags for A/B testing overlays.',
  'Use Portal for date pickers that need to render above form fields.',
  'Use Portal for sidebar drawers that slide over main content.',
  'Set Portal withWrapper for consistent overlay container structure.',
  'Use Portal for color pickers that float above input fields.',
  'Use Portal for rich text editor toolbars that float above content.',
];

export default { component, compositionTips };
