const component = {
  name: 'Price',
  import: "import { Price } from 'gd-design-library'",
  description:
    'Price display component for showing product prices with support for current and discounted pricing, currency formatting, and customizable styling for e-commerce applications.',
  a2uiName: 'price',
  category: 'Content & Media',
  complexity: 'Low',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Lightweight',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~1KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'currentValue',
      type: 'string',
      description: 'Formatted current price string (e.g. "29.99", "1,299")',
      required: true,
    },
    { name: 'oldValue', type: 'string', description: 'Original/struck-through price for showing discounts' },
    { name: 'currencySymbol', type: 'string', description: 'Currency symbol to display (e.g. "$", "€", "£")' },
    {
      name: 'currencySymbolPosition',
      type: "'before' | 'after'",
      description:
        'Position of currency symbol. "before" (default): "$29.99"; "after": "29,99 €" (European convention)',
      enum: ['before', 'after'] as const,
    },
    { name: 'size', type: "'sm' | 'md' | 'lg'", description: 'Size variant of the price text' },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the price component' },
  ],
  examples: [
    '// US convention (symbol before, period decimal)\n<Price currentValue="29.99" currencySymbol="$" />',
    '<Price currentValue="1,299" oldValue="1,499" currencySymbol="$" />',
    '// European convention (symbol after, comma decimal, space thousands)\n<Price currentValue="29,99" currencySymbol="€" currencySymbolPosition="after" />',
    '<Price currentValue="1 299,99" oldValue="1 499,99" currencySymbol="€" currencySymbolPosition="after" />',
    '// Whole numbers — no trailing zeros\n<Price currentValue="99" currencySymbol="$" />',
    '<Price currentValue="99" currencySymbol="€" currencySymbolPosition="after" />',
  ],
};

const compositionTips: string[] = [
  'Show oldValue with strikethrough styling to indicate discounts.',
  'Localize and format currency consistently across the app.',
  'Pair Price with Counter to show dynamic totals in carts.',
  'Use semantic markup (e.g., aria-label) to announce discounts for screen readers.',
  'Use Price with currentValue for regular product pricing display in product cards and listings.',
  'Apply Price with both currentValue and oldValue to show discounts and sale prices effectively.',
  'Set Price oldValue with strikethrough styling via CSS to clearly indicate original pricing.',
  'Use Price currentValue with bold or larger font via className for emphasis on final price.',
  'Apply Price in Card components alongside product images and descriptions for e-commerce layouts.',
  'Combine Price with Typography for currency symbols or additional pricing context like "per month".',
  'Use Price className to apply consistent pricing styles across all product displays.',
  'Apply Price with InlineNotification to highlight special offers or limited-time discounts.',
  'Set Price currentValue dynamically based on user selection of product variants or quantities.',
  'Use Price with conditional rendering to show member vs non-member pricing.',
  'Apply Price oldValue only when discount is active to avoid confusion with regular pricing.',
  'Combine Price with Badge components to show discount percentages like "30% OFF".',
  'Use Price in product comparison tables with consistent alignment for easy price comparison.',
  'Apply Price with responsive font sizes via className for mobile-optimized displays.',
  'Set Price with locale-specific currency formatting for international e-commerce sites.',
  'Use Price alongside Counter component for quantity-based pricing calculations.',
  'Apply Price with animation effects when prices update due to promotions or cart changes.',
  'Combine Price with Tooltip to explain pricing details like tax inclusion or shipping costs.',
  'Use Price currentValue with color coding (red for sale, green for deals) for visual pricing cues.',
  'Apply Price in ContentCarousel for featured products with prominent pricing display.',
  'Set Price with consistent decimal places for professional pricing presentation.',
  'Use Price with subscription indicators showing recurring payment terms.',
  'Apply Price oldValue with smaller font size via className to de-emphasize original price.',
  'Combine Price with Icon components for price drop indicators or trending pricing.',
  'Use Price in checkout flows showing item prices, subtotals, and totals consistently.',
  'Apply Price with strikethrough animation when discounts are applied in real-time.',
  'Set Price className with theme-aware colors for dark/light mode compatibility.',
  'Use Price with price range display for variable pricing products using two Price components.',
  'Apply Price in Select option rendering for tier-based pricing selection.',
  'Combine Price with Timer components for countdown sales showing time-limited pricing.',
  'Use Price currentValue with "FREE" text for zero-cost items or promotional giveaways.',
  'Apply Price with shipping cost indicators integrated into total price display.',
  'Set Price with consistent spacing from product titles and descriptions for visual hierarchy.',
  'Use Price in order history showing historical pricing at time of purchase.',
  'Apply Price with currency conversion tooltips for international customers.',
  'Combine Price with installment payment options showing monthly payment amounts.',
  "Use Price oldValue to show MSRP (Manufacturer's Suggested Retail Price) vs actual price.",
  'Apply Price with bulk pricing tiers showing different prices for quantity breaks.',
  'Set Price with accessibility attributes ensuring screen readers announce prices correctly.',
  'Use Price in email templates for order confirmations and promotional campaigns.',
  'Apply Price with dynamic updates based on promo code application in cart.',
  'Combine Price with stock availability indicators for pricing based on inventory.',
  'Use Price currentValue with unit pricing display like "per kg" or "per item".',
  'Apply Price with consistent formatting for thousands separators and decimal points.',
  'Set Price className for sale items with special background or border highlighting.',
  'Use Price in wishlist displays showing current vs saved pricing for price tracking.',
  'Apply Price with price match guarantee badges or lowest price indicators.',
  'Combine Price with reviews/ratings for value perception in product displays.',
  'Use Price with clear visual hierarchy making current price most prominent.',
];

export default { component, compositionTips };
