const component = {
  name: 'ProgressBar',
  import: "import { ProgressBar } from 'gd-design-library'",
  description:
    'Visual progress indicator component that displays task completion status with determinate or indeterminate states, customizable colors, and optional percentage display for tracking operations, uploads, or multi-step processes.',
  a2uiName: 'progress-bar',
  category: 'Feedback & Status',
  complexity: 'Low',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Lightweight',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~1KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    { name: 'label', type: 'string', description: 'Optional visible label rendered alongside the progress bar' },
    { name: 'value', type: 'number', description: 'Progress value from 0 to 100 (omit for indeterminate mode)' },
    { name: 'indeterminate', type: 'boolean', description: 'Show animated indeterminate mode for unknown durations' },
    { name: 'showPercentage', type: 'boolean', description: 'Show numeric percentage label (default: false)' },
    {
      name: 'fillColor',
      type: 'string',
      description:
        'Color of the filled progress track. Prefer theme color token paths (for example "bg.fill.primary" or "bg.fill.success.primary.default") before raw CSS/hex colors.',
    },
    {
      name: 'backgroundColor',
      type: 'string',
      description:
        'Background track color. Prefer theme color token paths (for example "bg.fill.disabled" or "bg.fill.info.secondary.default") before raw CSS/hex colors.',
    },
    { name: 'ariaLabel', type: 'string', description: 'Accessible label announced to screen readers' },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the progress bar' },
  ],
  examples: [
    '<ProgressBar value={75} showPercentage />',
    '<ProgressBar indeterminate aria-label="Loading content" />',
    '<ProgressBar value={50} fillColor="bg.fill.success.primary.default" backgroundColor="bg.fill.info.secondary.default" />',
    '<ProgressBar value={100} showPercentage fillColor="bg.fill.primary" aria-label="Upload complete" />',
    '<ProgressBar value={25} styles={{width: "100%"}} className="upload-progress" />',
  ],
};

const compositionTips: string[] = [
  'Use indeterminate for unknown durations; switch to determinate when progress is known.',
  'Announce progress updates for screen readers via aria-live when appropriate.',
  'Avoid showing percentage when space is tight; use tooltip or label nearby.',
  'Pick contrasting fill/background colors for sufficient visual contrast.',
  'Use ProgressBar with value prop for determinate progress tracking when duration or steps are known.',
  'Apply ProgressBar indeterminate={true} for operations with unknown duration like initial data fetching.',
  'Set ProgressBar showPercentage={true} to display numeric progress for user clarity in uploads or downloads.',
  'Use ProgressBar fillColor with semantic theme tokens for success, info, warning, or error progress states.',
  'Apply ProgressBar in file upload interfaces updating value based on upload percentage.',
  'Combine ProgressBar with InlineNotification above or below for status messages during operations.',
  'Use ProgressBar value={0} initially and update to 100 on completion for clear start/end states.',
  'Apply ProgressBar backgroundColor to match container background for seamless integration.',
  'Set ProgressBar with consistent height via styles for uniform appearance across the app.',
  'Use ProgressBar in multi-step forms showing overall completion across all steps.',
  'Apply ProgressBar indeterminate in Button or Card during async operations.',
  'Combine ProgressBar with Typography showing step labels like "Step 2 of 5" for context.',
  'Use ProgressBar aria-label with descriptive text for screen reader accessibility.',
  'Apply ProgressBar with animation transitions for smooth value changes.',
  'Set ProgressBar width="100%" via styles for responsive full-width progress indicators.',
  'Use ProgressBar in Modal headers or footers for operation progress within dialogs.',
  'Apply ProgressBar with theme-token fillColor values to stay aligned with the active brand palette.',
  'Combine ProgressBar with Cancel button for interruptible long-running operations.',
  'Use ProgressBar value calculated from array.filter().length for item processing progress.',
  'Apply ProgressBar showPercentage={false} for clean minimal progress indicators.',
  'Set ProgressBar in Table rows for individual item processing status.',
  'Use ProgressBar with WebSocket updates for real-time operation progress.',
  'Apply ProgressBar indeterminate with reduced opacity for subtle loading states.',
  'Combine ProgressBar with estimated time remaining text for better user expectations.',
  'Use ProgressBar in dashboard widgets for goal completion or quota tracking.',
  'Apply ProgressBar with stepped increments (25%, 50%, 75%) for chunked operations.',
  'Set ProgressBar fillColor conditionally based on value thresholds for status indication.',
  'Use ProgressBar in onboarding flows showing profile completion percentage.',
  'Apply ProgressBar with icon indicators at milestones (checkmarks at 25%, 50%, 75%, 100%).',
  'Combine ProgressBar with Loader component switching based on operation phase.',
  'Use ProgressBar for media playback progress with value from currentTime/duration.',
  'Apply ProgressBar in Card components for project or task completion status.',
  'Set ProgressBar with gradient fillColor via CSS for modern visual effects.',
  'Use ProgressBar value from API polling for server-side operation tracking.',
  'Apply ProgressBar with tooltip showing detailed progress information on hover.',
  'Combine ProgressBar with pause/resume controls for manageable long operations.',
  'Use ProgressBar in survey or quiz interfaces showing question progress.',
  'Apply ProgressBar with segmented appearance for discrete step visualization.',
  'Set ProgressBar in sidebars for storage usage or quota consumption display.',
  'Use ProgressBar indeterminate during connection establishment or handshake phases.',
  'Apply ProgressBar with error state styling when operations fail mid-progress.',
  'Combine ProgressBar with retry button appearing on failure for recovery options.',
  'Use ProgressBar for scroll progress indicators in long articles or documents.',
  'Apply ProgressBar with micro-animations at 100% completion for success feedback.',
  'Set ProgressBar with reduced motion preferences for accessibility compliance.',
  'Use ProgressBar in batch operations showing overall progress across multiple items.',
  'Apply ProgressBar with stacked bars for multi-category progress tracking.',
  'Combine ProgressBar with sound notifications at completion for background tasks.',
  'Use ProgressBar value with localStorage to persist progress across page refreshes.',
];

export default { component, compositionTips };
