const component = {
  name: 'RadioGroup',
  import: "import { RadioGroup } from 'gd-design-library'",
  description:
    'Radio button group component for single selection from multiple options with flexible layout variants (row, column, grid) and customization options including images, colors, tooltips, and custom rendering.',
  a2uiName: 'radio-group',
  category: 'Forms & Input',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~3KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'options',
      type: 'Array<{ value: string; label: string; disabled?: boolean; hex?: string; image?: string; tooltip?: string }>',
      description:
        'Array of radio options. Each option has value, label, optional disabled, and visual extras (theme-token-or-hex swatch color, image URL, tooltip). Prefer theme tokens in options[].hex before raw hex colors.',
      required: true,
    },
    { name: 'value', type: 'string', description: 'Currently selected value (controlled)' },
    { name: 'defaultValue', type: 'string', description: 'Initially selected value (uncontrolled)' },
    {
      name: 'variant',
      type: 'string',
      description: 'Layout arrangement of the radio items',
      enum: ['row', 'column', 'grid'] as const,
      default: 'row',
    },
    { name: 'size', type: 'string', description: 'Size of the radio items', enum: ['sm', 'md'] as const },
    { name: 'gutter', type: 'string | number', description: 'Spacing between radio items' },
    { name: 'gridColumns', type: 'number | string', description: 'Number of columns for grid variant' },
    { name: 'gridRows', type: 'number | string', description: 'Number of rows for grid variant' },
    { name: 'gridColumnGutter', type: 'string | number', description: 'Horizontal gap between grid items' },
    { name: 'gridRowGutter', type: 'string | number', description: 'Vertical gap between grid rows' },
    { name: 'wrapItems', type: 'boolean', description: 'Whether items should wrap in row/column layouts' },
    { name: 'align', type: 'string', description: 'Flex align-items value for the group layout' },
    { name: 'justify', type: 'string', description: 'Flex justify-content value for the group layout' },
    { name: 'itemWidth', type: 'string', description: 'Width of each radio item' },
    { name: 'itemHeight', type: 'string', description: 'Height of each radio item' },
    { name: 'name', type: 'string', description: 'HTML name attribute for the radio group (for form submission)' },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the radio group' },
    { name: 'actions', type: 'string[]', description: 'Action IDs from ui.actions to trigger on value change' },
  ],
  examples: [
    '<RadioGroup options={[{label: "Option 1", value: "1"}, {label: "Option 2", value: "2"}]} value={selected} onChange={setSelected} />',
    '<RadioGroup variant="column" options={sizeOptions} defaultValue="medium" name="size-selection" />',
    '<RadioGroup variant="grid" gridColumns={3} gridColumnGutter="12px" gridRowGutter="12px" options={colorOptions.map(c => ({...c, hex: c.token}))} onChange={handleColorChange} />',
    '<RadioGroup options={plans} renderOption={({option, isSelected}) => <Card isHighlighted={isSelected}>{option.label}</Card>} />',
    '<RadioGroup options={themes.map(t => ({label: t.name, value: t.id, image: t.preview, tooltip: t.description}))} itemWidth="150px" itemHeight="100px" />',
  ],
};

const compositionTips: string[] = [
  'Use Row for short option sets; Column for longer labels or many items; Grid for visual selections.',
  'Keep one option selected at all times when value is required; provide defaultValue for uncontrolled use.',
  'Use renderOption to enrich options with icons, images, or badges.',
  'Ensure keyboard navigation (arrow keys) and focus styles for accessibility.',
  'Use RadioGroup for mutually exclusive selections like payment methods, shipping options, or plan tiers.',
  'Apply RadioGroup variant="row" (default) for horizontal layouts with few options (2-4 items).',
  'Set RadioGroup variant="column" for vertical lists with many options or when labels are long.',
  'Use RadioGroup variant="grid" with gridColumns for visual selection interfaces like color or theme pickers.',
  'Apply RadioGroup value with controlled components and onChange for state management integration.',
  'Combine RadioGroup with Card components in renderOption for rich option displays with descriptions.',
  'Use RadioGroup defaultValue for uncontrolled components with initial selection.',
  'Apply RadioGroup options with disabled property for temporarily unavailable choices.',
  'Set RadioGroup itemWidth and itemHeight for uniform option sizes in visual selectors.',
  'Use RadioGroup options with hex property for color-coded selections, preferring theme token paths before raw hex values.',
  'Apply RadioGroup options with image property for visual selection interfaces like avatars or patterns.',
  'Combine RadioGroup with Tooltip via options.tooltip for additional context on hover.',
  'Use RadioGroup renderOption to create custom layouts with icons, badges, or nested content.',
  'Apply RadioGroup gutter with consistent spacing tokens for aligned form layouts.',
  'Set RadioGroup gridColumns={2} or gridColumns={3} for responsive grid layouts on different viewports.',
  'Use RadioGroup name attribute for proper form submission with unique group identification.',
  'Apply RadioGroup with payload in options for rich data handling in renderOption function.',
  'Combine RadioGroup with InlineNotification for validation messages or selection confirmations.',
  'Use RadioGroup onChange with analytics tracking for user preference monitoring.',
  'Apply RadioGroup variant="grid" with equal itemWidth/itemHeight for tile-based selections.',
  'Set RadioGroup gridColumnGutter and gridRowGutter for precise grid spacing control.',
  'Use RadioGroup with conditional option rendering based on user permissions or feature flags.',
  'Apply RadioGroup renderOption with Typography for consistent text styling across options.',
  'Combine RadioGroup with Form component for integrated form validation and submission.',
  'Use RadioGroup options array built dynamically from API responses or configuration.',
  'Apply RadioGroup with keyboard navigation support (arrow keys) for accessibility.',
  'Set RadioGroup styles for custom container styling matching design requirements.',
  'Use RadioGroup with icons in renderOption for visual enhancement of text options.',
  'Apply RadioGroup variant="column" inside Card components for organized settings sections.',
  'Combine RadioGroup with disabled state during form submission to prevent changes.',
  'Use RadioGroup defaultValue with localStorage for persisting user preferences.',
  'Apply RadioGroup with responsive variant switching based on viewport size.',
  'Set RadioGroup options with consistent naming patterns for maintainable code.',
  'Use RadioGroup renderOption with conditional styling based on isSelected state.',
  'Apply RadioGroup with error state styling when selection is required but missing.',
  'Combine RadioGroup with Select as alternative UI for many options (>10 items).',
  'Use RadioGroup itemWidth="100%" for full-width options in mobile layouts.',
  'Apply RadioGroup with visual feedback animations on selection change.',
  'Set RadioGroup with aria-label for screen reader context when label is not visible.',
  'Use RadioGroup options with rich content in renderOption including prices or descriptions.',
  'Apply RadioGroup variant="grid" for image galleries or visual option matrices.',
  'Combine RadioGroup with Counter or Input fields that update based on selection.',
  'Use RadioGroup with consistent option ordering (alphabetical, by price, by popularity).',
  'Apply RadioGroup gridRows with gridColumns for fixed grid dimensions.',
  'Set RadioGroup with custom focus styles for keyboard navigation visibility.',
  'Use RadioGroup renderOption with Badge components for status or count indicators.',
  'Apply RadioGroup with section headers using Typography above option groups.',
  'Combine RadioGroup with real-time validation showing selection requirements.',
  'Use RadioGroup options with tooltips for complex options needing explanation.',
  'Apply RadioGroup with consistent patterns across similar selection contexts for familiar UX.',
];

export default { component, compositionTips };
