const component = {
  name: 'Rating',
  import: "import { Rating } from 'gd-design-library'",
  description:
    'Interactive star rating component for collecting user feedback, displaying ratings, or showing quality indicators with customizable maximum value, read-only mode, and various size options.',
  a2uiName: 'rating',
  category: 'Forms & Input',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~2KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    { name: 'value', type: 'number', description: 'Current rating value (0–max), supports fractional values like 3.5' },
    { name: 'defaultValue', type: 'number', description: 'Initial rating value for uncontrolled usage' },
    { name: 'max', type: 'number', description: 'Total number of stars (default 5)' },
    { name: 'readOnly', type: 'boolean', description: 'When true, rating is display-only and non-interactive' },
    {
      name: 'size',
      type: 'string',
      description: 'Size variant of the rating component',
      enum: ['sm', 'md', 'lg'] as const,
    },
    { name: 'name', type: 'string', description: 'HTML name attribute for grouping radio inputs' },
    { name: 'actions', type: 'string[]', description: 'Action IDs from ui.actions to trigger when the rating changes' },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the rating component' },
  ],
  examples: [
    '<Rating value={4} max={5} onChange={handleRatingChange} />',
    '<Rating value={3.5} readOnly size="lg" />',
    '<Rating max={10} value={7} color="#FFD700" />',
    '<Rating value={5} max={5} readOnly className="product-rating" />',
    '<Rating value={0} max={5} onChange={setUserRating} size="sm" />',
  ],
};

const compositionTips: string[] = [
  'Use readOnly for display-only ratings; enable onChange for interactive feedback.',
  'Allow half or fractional values only if visually supported; otherwise stick to integers.',
  'Choose size based on context; smaller in dense lists, larger on product details.',
  'Provide sufficient color contrast; use theme colors for consistency.',

  'Use Rating with value prop for displaying existing ratings in product cards, reviews, or feedback sections.',
  'Apply Rating readOnly={true} for display-only ratings where user interaction is not needed.',
  'Set Rating max={10} for more granular rating scales in detailed evaluation forms.',
  'Use Rating onChange handler to update state and trigger side effects like saving to database.',
  'Apply Rating size="sm" in compact UI elements like table cells or inline with text.',
  'Combine Rating with Typography to show numeric value alongside stars like "4.5 out of 5".',
  'Use Rating color prop with brand colors or semantic colors (gold for premium, etc.).',
  'Apply Rating in Card components for product reviews with consistent spacing.',
  'Set Rating gap prop to adjust spacing between stars for visual balance.',
  'Use Rating with conditional rendering to show only after user interaction or purchase.',
  'Apply Rating alignItems="start" in forms where left alignment is preferred.',
  'Combine Rating with InlineNotification to show feedback after rating submission.',
  'Use Rating value with decimal values for accurate average rating display.',
  'Apply Rating size="lg" for prominent rating collection in feedback modals.',
  'Set Rating className for applying custom hover effects or animations.',
  'Use Rating with disabled state during form submission to prevent changes.',
  'Apply Rating in review sections with count display showing number of ratings.',
  'Combine Rating with Button for submit action after rating selection.',
  'Use Rating readOnly with value from API for displaying aggregate ratings.',
  'Apply Rating with tooltip showing rating descriptions on hover.',
  'Set Rating max={3} for simple satisfaction ratings (poor, average, excellent).',
  'Use Rating in comparison tables for feature or quality ratings.',
  'Apply Rating with localStorage to persist user ratings across sessions.',
  'Combine Rating with filter functionality to filter items by rating ranges.',
  'Use Rating onChange with debouncing for auto-save functionality.',
  'Apply Rating in surveys with multiple rating questions in Column layout.',
  'Set Rating with aria-label for accessibility describing what is being rated.',
  'Use Rating with animation on value change for visual feedback.',
  'Apply Rating size based on viewport for responsive design.',
  'Combine Rating with review text in Card for complete review display.',
  'Use Rating with half-star values for more precise rating display.',
  'Apply Rating in sortable lists as a sorting criterion.',
  'Set Rating with custom star icons via CSS for unique visual style.',
  'Use Rating readOnly={false} in forms requiring user rating input.',
  'Apply Rating with validation ensuring rating is provided before submission.',
  'Combine Rating with date/time stamps for historical rating tracking.',
  'Use Rating in dashboards showing average ratings with trend indicators.',
  'Apply Rating with different max values for different rating contexts.',
  'Set Rating with consistent color scheme across all rating instances.',
  'Use Rating onChange to trigger analytics events for user feedback tracking.',
  'Apply Rating in modal dialogs for post-interaction feedback collection.',
  'Combine Rating with user Avatar for personalized review displays.',
  'Use Rating with loading state while fetching rating data from API.',
  'Apply Rating in ContentCarousel for testimonials with ratings.',
  'Set Rating with keyboard navigation support for accessibility.',
  'Use Rating with visual indicators for rating thresholds (poor/fair/good/excellent).',
  'Apply Rating in product comparisons showing ratings side by side.',
  'Combine Rating with percentage display showing distribution of ratings.',
  'Use Rating with responsive gap adjustment for mobile optimization.',
];

export default { component, compositionTips };
