const component = {
  name: 'Scroll',
  import: "import { Scroll } from 'gd-design-library'",
  description:
    'Scrollable container with configurable vertical and horizontal scrollbar visibility plus optional auto-hide behavior.',
  a2uiName: 'scroll',
  category: 'Layout & Structure',
  complexity: 'Low',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Lightweight',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~1KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'children',
      type: 'A2UIComponent[]',
      description: 'Nested A2UI child components rendered inside the scroll container',
      required: true,
    },
    {
      name: 'vertical',
      type: 'string',
      description: 'Vertical scrollbar visibility',
      enum: ['hidden', 'visible', 'auto'] as const,
      default: 'auto',
    },
    {
      name: 'horizontal',
      type: 'string',
      description: 'Horizontal scrollbar visibility',
      enum: ['hidden', 'visible', 'auto'] as const,
      default: 'auto',
    },
    {
      name: 'autoHide',
      type: 'boolean',
      description: 'Whether visible scrollbars fade out when the user stops scrolling',
      default: false,
    },
    {
      name: 'styling',
      type: 'object',
      description: 'CSS style overrides — include maxHeight/height to constrain the scrollable area',
    },
  ],
  examples: [
    '<Scroll vertical="auto" horizontal="hidden"><LongContent /></Scroll>',
    '<Scroll vertical="visible" styling={{maxHeight: "400px"}}>{tableData}</Scroll>',
    '<Scroll horizontal="auto" vertical="hidden"><WideTable /></Scroll>',
    '<Scroll styling={{height: "300px", border: "1px solid #ccc"}}>{messages}</Scroll>',
    '<Scroll vertical="auto" autoHide><ArticleContent /></Scroll>',
    '<Scroll vertical="auto" autoHide styling={{height: "500px"}}><ChatMessages /></Scroll>',
  ],
};

const compositionTips: string[] = [
  'Use Scroll with autoHide for content-focused interfaces where scrollbars should fade when not in use.',
  'Apply Scroll autoHide in article readers or documentation pages for minimal visual distraction.',
  'Set Scroll autoHide for chat interfaces to keep focus on messages rather than UI chrome.',
  'Combine Scroll autoHide with vertical="auto" for clean reading experiences.',
  'Use Scroll autoHide in modal dialogs to maintain focus on content during reading.',
  'Apply Scroll autoHide for image galleries or media viewers to maximize content visibility.',
  'Set Scroll autoHide false (default) when users need constant scroll position awareness.',
  'Use Scroll with maxHeight to create constrained scrollable regions.',
  'Hide horizontal scrolling for text content to prevent sideways scroll.',
  'Combine Scroll with Card to keep long content within visual boundaries.',
  'Adjust vertical/horizontal props to match desired overflow behavior.',
  'Use Scroll with vertical="auto" for content that may exceed container height naturally.',
  'Apply Scroll horizontal="hidden" to prevent horizontal scrolling in fixed-width layouts.',
  'Set Scroll vertical="visible" to always show scrollbar for consistent layout width.',
  'Use Scroll with styling.maxHeight to create fixed-height scrollable areas.',
  'Apply Scroll horizontal="auto" for tables or content that may be wider than viewport.',
  'Combine Scroll with Card for scrollable content sections with defined boundaries.',
  'Use Scroll vertical="hidden" horizontal="auto" for horizontal scrolling galleries.',
  'Apply Scroll with styling.height for chat message containers or logs.',
  'Set Scroll with overflow-y: auto equivalent using vertical="auto" for responsive content.',
  'Use Scroll inside Modal children for long form content or terms and conditions.',
  'Apply Scroll with minHeight and maxHeight for flexible yet bounded content areas.',
  'Combine Scroll with List for long scrollable lists with proper overflow handling.',
  'Use Scroll vertical="visible" in data tables to indicate more content availability.',
  'Apply Scroll with styling.padding to create a scrollable area with inner spacing.',
  'Set Scroll horizontal="hidden" with word-wrap for text content to prevent horizontal overflow.',
  'Use Scroll with dynamic height based on viewport for responsive scrollable areas.',
  'Apply Scroll in ChatContainer children for scrollable message history.',
  'Combine Scroll with sticky headers using position fixed for table headers.',
  'Use Scroll with styling.scrollBehavior for smooth scrolling animations.',
  'Apply Scroll vertical="auto" in Select dropdown for long option lists.',
  'Set Scroll with custom scrollbar styling via styling for branded appearance.',
  'Use Scroll horizontal="visible" for code blocks or preformatted text.',
  'Apply Scroll with styling.flex = "1 1 auto" inside FlexContainer for flexible scrollable areas.',
  'Combine Scroll with virtualization libraries for performance with large datasets.',
  'Use Scroll in sidebar navigation for long menu lists with preserved header/footer.',
  'Apply Scroll with styling.scrollSnapType for paginated or carousel-like scrolling.',
  'Set Scroll vertical="hidden" with programmatic scrolling for controlled navigation.',
  'Use Scroll with intersection observer for infinite scrolling implementations.',
  'Apply Scroll in Form for long forms while keeping submit button visible.',
  'Combine Scroll with Column inside for vertically scrollable content with spacing.',
  'Use Scroll horizontal="auto" for responsive tables on mobile devices.',
  'Apply Scroll with styling.border to visually indicate scrollable area boundaries.',
  'Set Scroll with scrollbar-width: thin via CSS for minimal scrollbar appearance.',
  'Use Scroll vertical="visible" horizontal="visible" for spreadsheet-like interfaces.',
  'Apply Scroll with keyboard navigation support for accessibility.',
  'Combine Scroll with anchor links for jump-to-section navigation within scrollable content.',
  'Use Scroll in Tab panels for scrollable tab content with fixed tab headers.',
  'Apply Scroll with resize observer to adjust scroll behavior on container resize.',
  'Set Scroll with styling.willChange = "scroll-position" for performance optimization.',
  'Use Scroll horizontal="hidden" with text-overflow: ellipsis for truncated text.',
  'Apply Scroll with custom scroll indicators for mobile-friendly scroll feedback.',
  'Combine Scroll with pull-to-refresh patterns for mobile applications.',
  'Use Scroll vertical="auto" as default for most scrollable content containers.',
  'Apply Scroll with consistent max-height values across similar UI components.',
  'Set Scroll with overflow-x and overflow-y control via horizontal and vertical props.',
  'Use Scroll in Image galleries with horizontal="auto" for horizontal browsing.',
  'Apply Scroll with scroll position restoration for maintaining position on navigation.',
  'Combine Scroll with loading indicators at scroll boundaries for paginated content.',
  'Use Scroll with ARIA attributes for screen reader scroll region announcements.',
];

export default { component, compositionTips };
