const component = {
  name: 'Search',
  import: "import { Search } from 'gd-design-library'",
  description:
    'Search input component with dropdown results list for real-time filtering and selection of items with customizable rendering and keyboard navigation support.',
  a2uiName: 'search',
  category: 'Forms & Input',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~3KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    { name: 'value', type: 'string', description: 'Current value of the search input field' },
    { name: 'placeholder', type: 'string', description: 'Placeholder text shown when search input is empty' },
    {
      name: 'options',
      type: 'Array<{ value: unknown; label: string; disabled?: boolean; icon?: string; href?: string }>',
      description: 'Array of search result options to display in the dropdown.',
    },
    {
      name: 'emptyItemsResult',
      type: 'string',
      description: 'Message displayed when no options match the current search value.',
    },
    {
      name: 'actions',
      type: 'string[]',
      description:
        'Optional action IDs triggered when the user types or selects an option. The renderer includes trigger metadata in the action payload.',
    },
    { name: 'width', type: 'string', description: 'Width of the search input field' },
    { name: 'styling', type: 'object', description: 'CSS style overrides including width for the search component' },
  ],
  examples: [
    '<Search items={products} value={query} onType={handleSearch} onSelect={handleSelect} placeholder="Search products..." />',
    '<Search items={users} renderOption={(user) => <FlexContainer><Avatar src={user.avatar} />{user.name}</FlexContainer>} />',
    '<Search items={filteredItems} emptyItemsResult="No matching items found" onType={handleRealTimeSearch} />',
  ],
};

const compositionTips: string[] = [
  'Use Search with items array for searchable dropdown selection combining text input with item selection.',
  'Apply Search onType callback for custom search logic implementation like fuzzy search or API calls.',
  'Set Search renderOption to customize result display with icons, badges, or rich content layouts.',
  'Use Search value with controlled component pattern and onType for state management.',
  'Apply Search emptyItemsResult with helpful message or suggestions when no matches are found.',
  'Combine Search with debounced onType for performance optimization with large datasets or API calls.',
  'Use Search placeholder with clear instructions like "Search by name, email, or ID" for user guidance.',
  'Apply Search width to match form field widths for consistent form layouts.',
  'Set Search maxHeight for dropdown to limit result list height with scrolling for many results.',
  'Use Search with Avatar in renderOption for user search with profile pictures.',
  'Apply Search disabled during data loading or based on user permissions.',
  'Combine Search with InlineNotification to show search tips or validation messages.',
  'Use Search aria-controls with results container ID for screen reader accessibility.',
  'Apply Search autoFocus for search-focused interfaces like search pages or modals.',
  'Set Search items with filtered array based on user input for client-side search.',
  'Use Search onSelect to navigate to selected item or update application state.',
  'Apply Search with Icon in renderOption for category or type indicators.',
  'Combine Search with keyboard navigation (arrow keys, Enter, Escape) for power users.',
  'Use Search in ChatContainer header for conversation or contact search.',
  'Apply Search with real-time filtering updating items array as user types.',
  'Set Search renderOption with Typography for consistent text styling in results.',
  'Use Search with empty state component in emptyItemsResult showing suggestions or help.',
  'Apply Search in Modal for focused search experiences without page navigation.',
  'Combine Search with Badge in renderOption to show counts or status indicators.',
  'Use Search items with async data fetching triggered by onType callback.',
  'Apply Search with highlight matching text in renderOption for better visibility.',
  'Set Search with minimum character requirement before showing results.',
  'Use Search in navigation bars for global site search functionality.',
  'Apply Search with recent searches or popular items when input is empty.',
  'Combine Search with category filtering to scope search to specific item types.',
  'Use Search renderOption with conditional rendering for different item types.',
  'Apply Search with loading state in emptyItemsResult while fetching results.',
  'Set Search with fuzzy matching algorithm for typo-tolerant search.',
  'Use Search in tables or lists for filtering displayed data.',
  'Apply Search with voice input integration for accessibility.',
  'Combine Search with Select for advanced search with multiple criteria.',
  'Use Search items with weighted results showing most relevant first.',
  'Apply Search with search history stored in localStorage for quick access.',
  'Set Search with auto-complete suggestions based on partial matches.',
  'Use Search in e-commerce for product search with image previews in renderOption.',
  'Apply Search with clear button in input for quick search reset.',
  'Combine Search with Router navigation on item selection for page routing.',
  'Use Search renderOption with Price component for product search results.',
  'Apply Search with keyboard shortcuts (Cmd/Ctrl+K) for quick access.',
  'Set Search with analytics tracking on searches and selections.',
  'Use Search in documentation sites for content search and navigation.',
  'Apply Search with synonyms or alternative terms for better matching.',
  'Combine Search with filters UI for refined search experiences.',
  'Use Search items with pagination for large result sets.',
  'Apply Search with responsive design adjusting width and layout on mobile.',
];

export default { component, compositionTips };
