const component = {
  name: 'Snackbar',
  import: "import { showSnackbar, SnackbarVariant, SnackbarPosition } from 'gd-design-library'",
  description:
    'Toast notification system for displaying temporary messages, alerts, and feedback with configurable positioning, duration, and styling. Use showSnackbar() function to trigger notifications.',
  a2uiName: 'snackbar',
  category: 'Feedback & Status',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~2KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    { name: 'label', type: 'string', description: 'Optional title text displayed at the top of the snackbar' },
    { name: 'value', type: 'string', description: 'Main body message of the snackbar', required: true },
    {
      name: 'variant',
      type: 'string',
      description: 'Visual style variant determining color and icon',
      enum: ['info', 'warning', 'error', 'success'] as const,
    },
    {
      name: 'placement',
      type: 'string',
      description: 'Screen placement of the snackbar overlay',
      enum: ['top-left', 'top-center', 'top-right', 'bottom-left', 'bottom-center', 'bottom-right'] as const,
    },
    {
      name: 'duration',
      type: 'number | null',
      description: 'Auto-dismiss duration in ms; null or 0 for persistent snackbars',
    },
    { name: 'dismissOnClick', type: 'boolean', description: 'Whether clicking the snackbar dismisses it' },
    {
      name: 'colored',
      type: 'boolean',
      description: 'Whether to use a colored (filled) background matching the variant',
    },
    { name: 'isAnimated', type: 'boolean', description: 'Whether the snackbar should animate in and out' },
    { name: 'icon', type: 'string', description: 'Optional icon name to display instead of the default variant icon' },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the snackbar surface' },
  ],
  examples: [
    'const SnackbarExample = () => { const onClick = () => { showSnackbar({ title: "Info", message: "This is an example of snackbar message.", variant: SnackbarVariant.Info, position: SnackbarPosition.TopRight, duration: 3000, dismissOnClick: true }); }; return ( <div> <SnackbarManager /> <Button onClick={onClick}>Show Snackbar</Button> </div> ); };',
    'showSnackbar({ title: "Success", message: "Your changes have been saved.", variant: SnackbarVariant.Success, position: SnackbarPosition.TopCenter });',
    'showSnackbar({ title: "Error", message: "Failed to save changes.", variant: SnackbarVariant.Error, action: <Button variant="text" onClick={handleRetry}>Retry</Button> });',
    'showSnackbar({ title: "Warning", message: "You have unsaved changes.", variant: SnackbarVariant.Warning, duration: 0, dismissOnClick: false });',
  ],
};

const compositionTips: string[] = [
  'Use variant to convey message severity (info, success, warning, error).',
  'Prefer TopRight or BottomRight positions to avoid overlapping core content.',
  'Set duration=0 for persistent messages that require explicit dismissal.',
  'Provide actionLabel and onAction for undo/redo or retry flows.',
  'Apply SnackbarVariant.Success for positive confirmations like save, create, or delete operations.',
  'Use SnackbarVariant.Error for API failures, validation errors, or system issues.',
  'Set SnackbarVariant.Warning for cautionary messages or potentially destructive actions.',
  'Apply SnackbarVariant.Info for neutral informational messages or tips.',
  'Use SnackbarPosition.TopRight or TopCenter for important notifications that need immediate attention.',
  'Apply SnackbarPosition.BottomRight or BottomCenter for less intrusive notifications.',
  'Set duration: 0 with dismissOnClick: false for critical messages that require user acknowledgment.',
  'Use shorter duration (2000-3000ms) for simple success messages, longer (5000-7000ms) for error details.',
  'Include action with a Button ReactNode for snackbars that offer user actions like "Undo" or "Retry".',
  'Call showSnackbar() in response to async operations completion or failure.',
  'Use onClose callback to track user interaction with notifications for analytics.',
  'Avoid showing multiple snackbars rapidly; batch or queue messages when appropriate.',
  'Keep snackbar messages concise; use title for category and message for details.',
  'Use consistent positioning throughout the app for predictable user experience.',
  'Show snackbars for background operations that complete while user is on different screen.',
  "Use snackbars instead of modals for non-blocking feedback that doesn't require immediate action.",
  'Combine snackbars with form validation to show submission results.',
  'Apply dismissOnClick: true for informational messages that users can quickly dismiss.',
  'Set dismissOnClick: false for important messages that should remain until duration expires.',
  'Use snackbars for real-time updates like "New message received" or "File uploaded".',
  'Show progress in snackbar message for operations like "Uploading... 60%".',
  'Apply consistent variant usage across similar operations for user familiarity.',
  'Use snackbar action prop with Button component for quick fixes like "Refresh" or "Try Again".',
  'Avoid overwhelming users with too many snackbars; prioritize important messages.',
  "Test snackbar positioning on mobile devices to ensure they don't obstruct important UI.",
  'Use snackbars for connection status changes like "Connection lost" or "Reconnected".',
  'Apply animation classes via className for custom entrance/exit effects.',
];

export default { component, compositionTips };
