const component = {
  name: 'Stepper',
  import: "import { Stepper } from 'gd-design-library'",
  description:
    'Progress indicator component that displays multi-step processes or workflows with visual feedback for completed, current, and upcoming steps. Supports custom step content, validation states, and interactive navigation between steps.',
  a2uiName: 'stepper',
  category: 'Navigation & Structure',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~3KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'options',
      type: 'Array<{ label: string; value?: string | number; validationStatus?: "success" | "error"; icon?: string }>',
      description:
        'Ordered step definitions. Each option can include a label, optional value, validationStatus, and optional icon.',
      required: true,
    },
    { name: 'value', type: 'number', description: 'Index of the currently active step (0-based)' },
    {
      name: 'isIconsView',
      type: 'boolean',
      description: 'Whether to render step indicators as icons instead of numbers',
    },
    {
      name: 'actions',
      type: 'string[]',
      description:
        'Action IDs from ui.actions to trigger when a step is clicked. Runtime payload includes index, status, value, and label.',
    },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the stepper' },
  ],
  examples: [
    '<Stepper steps={[{label: "Details"}, {label: "Payment"}, {label: "Review"}]} activeStep={1} />',
    '<Stepper steps={wizardSteps} activeStep={currentStep} onStepClick={handleStepClick} />',
    '<Stepper steps={[{label: "Step 1", validationStatus: "success"}, {label: "Step 2", validationStatus: "error"}]} activeStep={1} />',
    '<Stepper steps={stepsWithIcons} isIconsView={true} activeStep={2} />',
    '<Stepper steps={[{label: "Upload", customView: <Icon name="upload" />}, {label: "Process"}, {label: "Complete"}]} activeStep={0} />',
  ],
};

const compositionTips: string[] = [
  'Use Stepper for multi-step wizards and checkout flows with clear progress.',
  'Keep step labels concise; add customView for icons or additional context.',
  'Allow clicking previous steps for quick navigation when business rules permit.',
  'Reflect validationStatus on steps to signal completion or errors.',
  'Persist activeStep in state or URL to keep progress across reloads.',
  'Use Stepper for multi-step forms or wizards with clear progression indicators showing completed, current, and upcoming steps.',
  'Apply Stepper activeStep with state management to track user progress through multi-page workflows.',
  'Set Stepper steps with validationStatus="success" for completed steps and "error" for steps requiring correction.',
  'Use Stepper onStepClick to enable navigation between steps for non-linear workflows where users can jump between sections.',
  'Apply Stepper isIconsView={true} for visual processes where icons better represent step content than numbers.',
  'Combine Stepper with Form validation setting validationStatus based on form field validity in each step.',
  'Use Stepper customView prop in steps for rich step indicators like avatars, icons, or progress percentages.',
  'Apply Stepper with disabled onStepClick for linear workflows requiring sequential step completion.',
  'Set Stepper activeStep={0} initially and increment after successful validation of current step content.',
  'Use Stepper in Modal for guided setup processes or configuration wizards with contained step navigation.',
  'Apply Stepper with consistent step labels keeping them short and action-oriented for clarity.',
  'Combine Stepper with InlineNotification to show step-specific instructions or validation messages.',
  'Use Stepper steps array built dynamically based on conditional logic for adaptive workflows.',
  'Apply Stepper with Card components wrapping step content for visually organized multi-step interfaces.',
  'Set Stepper with responsive design hiding step labels on mobile, showing only icons or numbers.',
  'Use Stepper validationStatus="error" with Tooltip on hover explaining what needs correction.',
  'Apply Stepper in checkout flows with steps like "Cart", "Shipping", "Payment", "Confirmation".',
  'Combine Stepper with router integration syncing activeStep with URL for deep-linkable wizard states.',
  'Use Stepper customView with Loader component for steps that are currently processing.',
  'Apply Stepper with aria-label describing the overall process for screen reader context.',
  'Set Stepper with transition animations between activeStep changes for smooth visual feedback.',
  'Use Stepper in onboarding flows with clear step count showing users their progress.',
  'Apply Stepper styles prop for custom colors matching brand guidelines for step indicators.',
  'Combine Stepper with Button navigation controls for "Previous" and "Next" step actions.',
  'Use Stepper with localStorage to persist wizard progress across browser sessions.',
  "Apply Stepper isIconsView with meaningful icons that clearly represent each step's purpose.",
  'Set Stepper with skip functionality using onStepClick for optional steps in the workflow.',
  'Use Stepper in user registration with steps for account info, profile setup, and confirmation.',
  'Apply Stepper with time estimates in step labels like "Step 1 (2 min)" for user expectations.',
  'Combine Stepper with progress percentage calculation based on activeStep for additional feedback.',
  'Use Stepper validationStatus updates in real-time as users complete step requirements.',
  'Apply Stepper with consistent height to prevent layout shifts when switching between steps.',
  'Set Stepper with breadcrumb-style navigation for alternative step visualization in compact spaces.',
  'Use Stepper in survey or questionnaire interfaces showing question groups as steps.',
  'Apply Stepper with keyboard navigation support using arrow keys for accessibility.',
  'Combine Stepper with analytics tracking to identify where users drop off in multi-step processes.',
  'Use Stepper customView with checkmarks for completed steps and X marks for failed validation.',
  'Apply Stepper with contextual help links or tooltips for each step providing additional guidance.',
  'Set Stepper with auto-advance functionality moving to next step after successful completion.',
  'Use Stepper in file upload workflows with steps for selection, validation, and processing.',
  'Apply Stepper with mobile-optimized layout stacking steps vertically on small screens.',
  'Combine Stepper with conditional step visibility based on user selections in previous steps.',
  'Use Stepper with error recovery allowing users to correct issues without losing progress.',
  'Apply Stepper styles with custom animations for step transitions and status changes.',
  'Set Stepper with summary view on final step showing all collected information for review.',
  'Use Stepper in tutorial or learning paths with steps representing lessons or modules.',
  'Apply Stepper with estimated completion time updated based on remaining steps.',
  'Combine Stepper with Modal or Drawer for space-efficient multi-step processes.',
  'Use Stepper validationStatus with async validation checking backend requirements.',
];

export default { component, compositionTips };
