const component = {
  name: 'Tabs',
  import: "import { Tabs } from 'gd-design-library'",
  description:
    'Navigation component that organizes content into separate views accessed through tabbed interfaces. Supports disabled states, notice counters, and keyboard navigation for accessible multi-section content organization.',
  a2uiName: 'tabs',
  category: 'Navigation & Structure',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~3KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'options',
      type: 'Array<{ label: string; value?: string | number; disabled?: boolean; noticeCounter?: number | string; icon?: string }>',
      description: 'Tab definitions in display order. Match each option with the child panel at the same index.',
      required: true,
    },
    {
      name: 'children',
      type: 'A2UIComponent[]',
      description: 'Tab panel content components. Children are matched to options by index.',
      required: true,
    },
    { name: 'value', type: 'number', description: 'Index of the currently active tab (0-based)' },
    {
      name: 'actions',
      type: 'string[]',
      description: 'Action IDs from ui.actions to trigger when the active tab changes',
    },
    { name: 'ariaLabel', type: 'string', description: 'Accessible label for the tab navigation element' },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the tabs component' },
  ],
  examples: [
    '<Tabs tabs={[{label: "Overview", content: <Overview />}, {label: "Details", content: <Details />}]} />',
    '<Tabs tabs={tabData} activeTab={1} onTabChange={handleTabChange} />',
    '<Tabs tabs={[{label: "Messages", content: <Messages />, noticeCounter: 5}, {label: "Settings", content: <Settings />}]} />',
    '<Tabs tabs={productTabs} ariaLabel="Product information tabs" styles={{borderBottom: "2px solid #ccc"}} />',
    '<Tabs tabs={[{label: "Active", content: <ActiveItems />}, {label: "Archived", content: <ArchivedItems />, isDisabled: true}]} />',
  ],
};

const compositionTips: string[] = [
  'Use Tabs to separate logically distinct content areas within the same page.',
  'Maintain keyboard accessibility: left/right arrows to navigate, Enter/Space to select.',
  'Show noticeCounter for tabs with updates (e.g., unread messages).',
  'Keep labels short; use Tooltip for longer descriptions if needed.',
  'Preserve active tab state across navigation when appropriate (e.g., via URL or context).',
  'Use Tabs for organizing related content into logical sections without page navigation.',
  'Apply Tabs with activeTab prop for controlled tab state management synced with URL or app state.',
  'Set Tabs with no more than 6 tabs to prevent overwhelming users with too many options.',
  'Use Tabs onTabChange to track analytics for most viewed sections and user navigation patterns.',
  'Apply Tabs with noticeCounter on specific tabs to indicate new or updated content requiring attention.',
  'Combine Tabs with Card components in content prop for visually structured tab panels.',
  'Use Tabs with meaningful labels that clearly describe the content within each tab section.',
  'Apply Tabs isDisabled prop for tabs that are conditionally available based on user permissions or data.',
  'Set Tabs activeTab={0} to always start with the most important or overview content visible.',
  'Use Tabs with consistent content structure across all tabs for predictable user experience.',
  'Apply Tabs ariaLabel for screen reader users to understand the purpose of the tab navigation.',
  'Combine Tabs with Form components in content for multi-step forms or categorized settings.',
  'Use Tabs with lazy loading in content prop to defer rendering of inactive tab content.',
  'Apply Tabs styles prop to customize border, padding, or background to match design requirements.',
  'Set Tabs with responsive design hiding tabs into dropdown menu on mobile devices.',
  'Use Tabs for filtering data views like Active/Completed/All in task management interfaces.',
  'Apply Tabs with icons in label prop using FlexContainer for visual tab identification.',
  'Combine Tabs with loading states in content while fetching tab-specific data.',
  'Use Tabs activeTab with useEffect to perform actions when specific tabs become active.',
  'Apply Tabs with keyboard navigation support using Space/Enter for accessibility compliance.',
  'Set Tabs with URL hash synchronization for deep-linkable tab states.',
  'Use Tabs for product information sections like Description/Specifications/Reviews.',
  'Apply Tabs with consistent height in content panels to prevent layout jumps.',
  'Combine Tabs with InlineNotification in content for tab-specific alerts or messages.',
  'Use Tabs noticeCounter with real-time updates for dynamic content indicators.',
  'Apply Tabs with overflow scrolling for many tabs using horizontal scroll on mobile.',
  'Set Tabs with animation transitions between tab panels for smooth content switching.',
  'Use Tabs for dashboard views organizing metrics into categories like Sales/Traffic/Conversions.',
  'Apply Tabs with nested Tabs in content for multi-level content organization.',
  'Combine Tabs with Select dropdown as alternative navigation for many options.',
  'Use Tabs isDisabled dynamically based on form validation or data availability.',
  'Apply Tabs with consistent tab order placing most-used tabs on the left.',
  'Set Tabs with vertical orientation via custom styles for sidebar navigation patterns.',
  'Use Tabs for comparison views showing different data sets or time periods.',
  'Apply Tabs with breadcrumbs above for hierarchical navigation context.',
  'Combine Tabs with charts or data visualizations in content for analytics interfaces.',
  'Use Tabs activeTab controlled by external navigation or search results.',
  'Apply Tabs with tooltips on disabled tabs explaining why they are unavailable.',
  'Set Tabs with consistent naming conventions for tab IDs for easier maintenance.',
  'Use Tabs for user profile sections like Account/Security/Preferences/Billing.',
  'Apply Tabs with responsive content adapting layout based on viewport size.',
  'Combine Tabs with router integration for tab navigation via browser back/forward.',
  'Use Tabs noticeCounter={0} to hide counter when no new content exists.',
  'Apply Tabs with print styles showing all tab content when printing.',
  'Set Tabs with focus management moving focus to content when tab activates.',
  'Use Tabs for documentation sections organizing API/Guides/Examples/FAQ.',
  'Apply Tabs with search functionality filtering or highlighting relevant tabs.',
  "Combine Tabs with localStorage to remember user's last active tab preference.",
  'Use Tabs styles with custom active tab indicators for branded experiences.',
];

export default { component, compositionTips };
