const component = {
  name: 'Textarea',
  import: "import { Textarea } from 'gd-design-library'",
  description: 'Multi-line text input with dynamic height adjustment, resize control, and helper text support.',
  a2uiName: 'textarea',
  category: 'Forms & Input',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~2KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    { name: 'placeholder', type: 'string', description: 'Placeholder text shown when textarea is empty' },
    { name: 'value', type: 'string', description: 'Controlled value of the textarea' },
    { name: 'disabled', type: 'boolean', description: 'Whether the textarea is disabled' },
    { name: 'readOnly', type: 'boolean', description: 'Whether the textarea is read-only' },
    {
      name: 'variant',
      type: 'string',
      description: 'Visual style variant of the textarea',
      enum: ['default', 'inline'] as const,
      default: 'default',
    },
    {
      name: 'color',
      type: 'string',
      description: 'Color state for validation feedback',
      enum: ['primary', 'error', 'success', 'warning'] as const,
    },
    {
      name: 'resize',
      type: 'string',
      description: 'Controls user resize behavior of the textarea',
      enum: ['none', 'both', 'horizontal', 'vertical'] as const,
      default: 'none',
    },
    {
      name: 'dynamicHeightAdjustment',
      type: 'boolean',
      description: 'Auto-grows the textarea height to fit content as user types',
    },
    { name: 'minHeight', type: 'string', description: 'Minimum height constraint (e.g. "120px")' },
    { name: 'maxHeight', type: 'string', description: 'Maximum height constraint (e.g. "400px")' },
    {
      name: 'maxCharacters',
      type: 'number',
      description: 'Maximum number of characters allowed; shows a character counter',
    },
    {
      name: 'ariaDescribedBy',
      type: 'string',
      description: 'ID of element describing the textarea for screen readers',
    },
    { name: 'actions', type: 'string[]', description: 'Action IDs from ui.actions to trigger on value change.' },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the textarea' },
  ],
  examples: [
    '<Textarea name="description" placeholder="Enter description..." rows={4} maxLength={500} />',
    '<Textarea value={comment} onChange={handleCommentChange} dynamicHeightAdjustment />',
    '<Textarea resize="vertical" minHeight="100px" maxHeight="400px" placeholder="Your message" />',
    '<Textarea readOnly defaultValue={logContent} rows={10} styles={{fontFamily: "monospace"}} />',
    '<Textarea name="feedback" placeholder="Share your thoughts..." dynamicHeightAdjustment maxLength={1000} />',
    '<Textarea name="code" placeholder="Paste your code here..." rows={8} styles={{fontFamily: "monospace"}} />',
    '<Textarea name="message" placeholder="Type your message..." resize="both" minHeight="80px" />',
    '<Textarea name="comment" placeholder="Add a comment..." variant="inline" />',
    '<Textarea name="email" placeholder="Enter email..." color="error" ariaDescribedBy="email-error" />',
    '<Textarea name="feedback" placeholder="Share feedback..." color="success" />',
    '<Textarea name="warning" placeholder="Enter warning..." color="warning" />',
  ],
  useCases: {
    'Form Input': [
      'Comments and feedback forms',
      'Product descriptions and reviews',
      'Contact form messages',
      'Survey responses and detailed answers',
      'Bug reports and issue descriptions',
    ],
    'Content Creation': [
      'Rich text editors and markdown composition',
      'Document editing and note-taking',
      'Blog post and article writing',
      'Code editors and script composition',
      'Email composition and templates',
    ],
    Communication: [
      'Chat message composition',
      'Social media post creation',
      'Forum discussions and replies',
      'Comment systems and threads',
      'Message boards and announcements',
    ],
    'Data Entry': [
      'Bulk text import and configuration',
      'Structured data input',
      'Log file viewing and editing',
      'Configuration file editing',
      'CSV and data processing',
    ],
    'Display Components': [
      'Read-only content display',
      'Formatted text viewers',
      'Documentation and help text',
      'Terms and conditions display',
      'User-generated content preview',
    ],
  },
  capabilities: {
    'Dynamic Sizing': [
      'Automatic height adjustment based on content',
      'Fixed row configurations for consistent layout',
      'User-controlled resizing with configurable directions',
      'Minimum and maximum height constraints',
      'Smooth transitions and animations',
    ],
    'Content Management': [
      'Character limits with built-in validation',
      'Default values for uncontrolled components',
      'Controlled and uncontrolled state patterns',
      'Real-time content validation and feedback',
      'Auto-save and draft functionality support',
    ],
    Accessibility: [
      'Full ARIA support and screen reader compatibility',
      'Keyboard navigation and focus management',
      'Proper labeling and description linking',
      'High contrast and color-blind friendly',
      'Touch-friendly for mobile devices',
    ],
    Performance: [
      'Efficient re-rendering with React patterns',
      'Minimal DOM manipulation and updates',
      'Optimized event handling and callbacks',
      'Memory-efficient content management',
      'Fast initial render and updates',
    ],
  },
};

const compositionTips: string[] = [
  'Use textarea for multi-line input such as comments, descriptions, notes, or messages.',
  'Use dynamicHeightAdjustment when the field should grow with content instead of showing early scrollbars.',
  'Use minHeight, maxHeight, and resize together to balance flexibility and layout stability.',
  'Use maxCharacters when the UI should show a live counter and enforce a clear text budget.',
  'Wire textarea changes through actions[] instead of raw onChange callbacks.',
];

export default { component, compositionTips };
