const component = {
  name: 'Tooltip',
  import: "import { Tooltip } from 'gd-design-library'",
  description:
    'Contextual information overlay component that displays helpful text on hover or focus, with smart positioning, configurable delays, and full accessibility support through portal rendering.',
  a2uiName: 'tooltip',
  category: 'Overlay & Dialog',
  complexity: 'Medium',
  accessibility: 'WCAG 2.1 AA Compliant',
  performance: 'Optimized',
  dependencies: ['@emotion/react', '@emotion/styled'],
  peerDependencies: ['react', 'react-dom'],
  bundleSize: '~2KB gzipped',
  browserSupport: 'All modern browsers',
  touchSupport: true,
  keyboardSupport: true,
  screenReaderSupport: true,
  props: [
    {
      name: 'content',
      type: 'string',
      description: 'Tooltip text displayed on hover or focus',
      required: true,
    },
    {
      name: 'children',
      type: 'A2UIComponent[]',
      description: 'The trigger component(s) that show the tooltip on hover or focus',
      required: true,
    },
    {
      name: 'placement',
      type: 'string',
      description: 'Position of the tooltip relative to the trigger element',
      enum: ['top', 'bottom', 'left', 'right'] as const,
      default: 'top',
    },
    { name: 'delay', type: 'number', description: 'Delay in milliseconds before the tooltip appears' },
    { name: 'gap', type: 'number', description: 'Pixel gap between the tooltip and the trigger element' },
    {
      name: 'as',
      type: 'string',
      description: 'HTML element to render the tooltip trigger wrapper as (e.g. "span" for inline contexts)',
    },
    { name: 'ariaLabel', type: 'string', description: 'Accessible label for the trigger wrapper element' },
    {
      name: 'ariaDescribedBy',
      type: 'string',
      description: 'Optional ARIA description id forwarded to the trigger wrapper',
    },
    { name: 'styling', type: 'object', description: 'CSS style overrides for the tooltip overlay' },
  ],
  examples: [
    '<Tooltip content="Save your changes" position="top"><Button>Save</Button></Tooltip>',
    '<Tooltip content="This field is required" position="right" delay={500}><Icon name="info" /></Tooltip>',
    '<Tooltip content={<Typography variant="caption" as="div">Click to copy</Typography>} position="bottom"><Typography>Copy text</Typography></Tooltip>',
    '<Tooltip content="Delete this item permanently" position="left" gap={15}><Button color="error" isIcon><Icon name="delete" /></Button></Tooltip>',
  ],
};

const compositionTips: string[] = [
  'Use Tooltip for short, helpful hints; avoid long instructional text.',
  'Prefer top or bottom positions to reduce overlap with the trigger.',
  'Increase delay slightly for touch devices to prevent accidental popups.',
  'Ensure ariaLabel/ariaDescribedBy provide accessible context.',
  'Use Tooltip content prop with concise, helpful text that adds value without stating the obvious.',
  'Apply Tooltip position="top" (default) for most cases, use other positions to avoid viewport edges.',
  'Set Tooltip delay with shorter times (100-200ms) for frequently used actions, longer (500ms+) for occasional hints.',
  'Use Tooltip gap to ensure proper spacing from trigger element, adjust for visual balance.',
  'Apply Tooltip on icon-only buttons to clarify their purpose with descriptive content text.',
  'Combine Tooltip with disabled elements to explain why an action is unavailable.',
  'Use Tooltip ariaLabel for trigger elements that need additional accessibility context.',
  'Apply Tooltip as="span" when wrapping inline elements within text content.',
  'Set Tooltip content with Typography components for rich formatted tooltip text.',
  'Use Tooltip on truncated text (text-overflow: ellipsis) to show full content on hover.',
  'Apply Tooltip position="right" or "left" for vertical lists to avoid covering adjacent items.',
  'Combine Tooltip with keyboard navigation support for accessibility compliance.',
  'Use Tooltip delay={0} for instant display in tutorial or onboarding flows.',
  'Apply Tooltip consistently across similar UI elements for predictable user experience.',
  'Set Tooltip with high contrast colors via styles for better readability.',
  'Use Tooltip on form field labels to provide format examples or requirements.',
  'Apply Tooltip position based on element location to prevent viewport overflow.',
  'Combine Tooltip with Icon components for info icons that reveal explanations.',
  'Use Tooltip content sparingly, avoid redundant information already visible in UI.',
  'Apply Tooltip on abbreviated text or acronyms to show full meanings.',
  'Set Tooltip gap larger for touch interfaces to prevent accidental triggers.',
  'Use Tooltip with conditional content based on application state or user permissions.',
  'Apply Tooltip in data tables for cell values that might be truncated or need context.',
  'Combine Tooltip with status indicators to explain what each status means.',
  'Use Tooltip delay consistently across the app for uniform interaction timing.',
  'Apply Tooltip on interactive elements only, avoid on decorative or disabled items.',
  'Set Tooltip content with line breaks or lists for structured information.',
  'Use Tooltip position="bottom" for elements at the top of viewport to ensure visibility.',
  'Apply Tooltip with Portal rendering to escape overflow hidden containers.',
  'Combine Tooltip with loading states to show progress or status information.',
  'Use Tooltip on navigation items to show full page names or descriptions.',
  'Apply Tooltip styles to match theme colors and maintain visual consistency.',
  'Set Tooltip with responsive content that adapts to mobile vs desktop contexts.',
  'Use Tooltip on badges or chips to provide additional context about counts or labels.',
  'Apply Tooltip ariaDescribedBy to link with detailed help text elements.',
  'Combine Tooltip with error states to show validation messages on hover.',
  'Use Tooltip on chart elements to display detailed data values.',
  'Apply Tooltip with z-index management via styles when inside modals or overlays.',
  'Set Tooltip content updates dynamically based on trigger element state.',
  'Use Tooltip on toolbar buttons to describe tool functions and shortcuts.',
  'Apply Tooltip with consistent max-width via styles to prevent overly wide tooltips.',
  'Combine Tooltip with internationalization for localized help text.',
  'Use Tooltip position="left" for RTL layouts or right-aligned elements.',
  'Apply Tooltip on links to show destination URLs or page descriptions.',
  'Set Tooltip with animation classes via className for custom enter/exit effects.',
  'Use Tooltip on image thumbnails to show larger preview or metadata.',
  'Apply Tooltip delay longer for decorative hints, shorter for functional guidance.',
  'Combine Tooltip with keyboard shortcuts display for power user features.',
  'Use Tooltip on save indicators to show last save time or status.',
  'Apply Tooltip with proper ARIA attributes for screen reader compatibility.',
];

export default { component, compositionTips };
